force-app/main/default/objects/Cost_Ledger__c/Cost_Ledger__c.object-meta.xml
<CustomObject>
    <label>Cost Ledger</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Cost ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cost Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cost_Ledger__c/fields/Amount_of_cost__c.field-meta.xml
<CustomField>
    <fullName>Amount_of_cost__c</fullName>
    <label>Amount of cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Ledger__c/fields/Cost_type__c.field-meta.xml
<CustomField>
    <fullName>Cost_type__c</fullName>
    <label>Cost type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cost_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Ledger__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Cost Ledgers</relationshipLabel>
    <relationshipName>Cost_Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cost_Ledger__c/fields/Marketing_campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing campaign</label>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Cost Ledgers</relationshipLabel>
    <relationshipName>Cost_Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cost_Ledger__c/fields/Marketing_Spend__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Spend__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spend period</label>
    <referenceTo>Marketing_Spend_Period__c</referenceTo>
    <relationshipLabel>Cost Ledgers</relationshipLabel>
    <relationshipName>Cost_Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cost_Ledger__c/fields/Time_of_cost__c.field-meta.xml
<CustomField>
    <fullName>Time_of_cost__c</fullName>
    <label>Time of cost</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Campaign</label>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Marketing Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cost_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Spend_Period__c/Marketing_Spend_Period__c.object-meta.xml
<CustomObject>
    <label>Marketing Spend</label>
    <nameField>
        <displayFormat>MSP-{0000}</displayFormat>
        <label>Marketing Spend Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Spends</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Spend_Period__c/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Campaign</label>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Marketing Spends</relationshipLabel>
    <relationshipName>Marketing_Spends</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Cost_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Advertising</fullName>
    </customValue>
    <customValue>
        <fullName>Meetings</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Cost Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CS_CostSystem_Controller_Test.cls
@isTest
public with sharing class CS_CostSystem_Controller_Test {
    @isTest
    private static void GetAllTheMarketingCampaign_test(){
        DFJ_TestDataFactory.CreateMarketCampaignsWithSpendPeriod(1,1);
        Test.startTest();
        CS_CostSystem_Controller.CampaignWrapper campignWrapperIns = CS_CostSystem_Controller.GetAllTheMarketingCampaign_Apex();
        Test.stopTest();
        System.assertEquals(1, campignWrapperIns.marketingCampaignList.size());
    }

    @isTest
    private static void SaveMarketingCampaign_test(){
        List<Marketing_Campaign__c> marketingCampaignList= DFJ_TestDataFactory.CreateMarketCampaigns(2);
        Test.startTest();
        String campaignId = CS_CostSystem_Controller.SaveMarketingCampaign(JSON.serialize(new Marketing_Campaign__c(Name='Test MC',Cost_Category__c='Other')));
        String campaignId2 = CS_CostSystem_Controller.SaveMarketingCampaign(JSON.serialize(''));
        String campaignId3 = CS_CostSystem_Controller.SaveMarketingCampaign('');
        Test.stopTest();
        Marketing_Campaign__c campaignInstance = [select Id,Name,Cost_Category__c FROM Marketing_Campaign__c WHERE Id=:campaignId LIMIT 1];
        System.assertEquals('Test MC', campaignInstance.Name);
        System.assertEquals(null, campaignId2);
        System.assertEquals(null, campaignId3);
    }

    @isTest
    private static void DeleteMarketingCampaign_test(){
        List<Marketing_Campaign__c> marketingCampaignList= DFJ_TestDataFactory.CreateMarketCampaigns(2);
        List<Marketing_Campaign__c> marketingCampaignList2= DFJ_TestDataFactory.CreateMarketCampaigns(2);
        Test.startTest();
        Boolean deleted = CS_CostSystem_Controller.DeleteMarketingCampaign('');
        CS_CostSystem_Controller.DeleteMarketingCampaign(marketingCampaignList[0].Id);
        delete marketingCampaignList2[0];
        Boolean deleted2 = CS_CostSystem_Controller.DeleteMarketingCampaign(marketingCampaignList2[0].Id);
        Test.stopTest();
        list<Marketing_Campaign__c> campaignInstance = [select Id,Name,Cost_Category__c FROM Marketing_Campaign__c LIMIT 10000];
        System.assertEquals(2, campaignInstance.size());
        System.assertEquals(false, deleted);
        System.assertEquals(false, deleted2);
    }

    @isTest
    private static void CalculateSpendAndNoSpendPeriod_Test(){
        List<Marketing_Spend_Period__c> marketingCampaignList= DFJ_TestDataFactory.CreateMarketCampaignsWithSpendPeriod(0,1);
        List<Marketing_Spend_Period__c> marketingCampaignList2 = DFJ_TestDataFactory.CreateMarketCampaignsWithSpendPeriod(1,1);
        Test.startTest();
        String processed = CS_CostSystem_Controller.CalculateSpendPerLead('');
        String processed2 = CS_CostSystem_Controller.CalculateSpendPerLead('1234');
        String processed3 = CS_CostSystem_Controller.CalculateSpendPerLead(marketingCampaignList[0].Id);
        String processed4 = CS_CostSystem_Controller.CalculateSpendPerLead(marketingCampaignList2[0].Id);
        Test.stopTest();
        System.assertEquals('Can not find spend period.', processed);
        System.assertEquals('Spend period not found.', processed2);
        System.assertEquals('Spend period not found.', processed2);
        System.assertEquals('lead records not found for this spend period.', processed4);
    }

    @isTest
    private static void CalculateSpendAndWithLead_Test(){
        List<Marketing_Spend_Period__c> marketingCampaignList= DFJ_TestDataFactory.CreateMarketCampaignsWithSpendPeriod(1,1);
        List<Lead> leadList = DFJ_TestDataFactory.CreateLeadWithHarAccepteFied(2);
        
        Test.startTest();
        String processed = CS_CostSystem_Controller.CalculateSpendPerLead(marketingCampaignList[0].Id);
        Test.stopTest();
        System.assertEquals('Total 2 leads processed and each one costs 500.00', processed);
    }

    @isTest
    private static void CalculateSpendAndWithLeadAndLedger_Test(){
        List<Marketing_Spend_Period__c> marketingSpendPeriod = DFJ_TestDataFactory.CreateMarketCampaignsWithSpendPeriod(1,1);
        List<Lead> leadList = DFJ_TestDataFactory.CreateleadWithLedger(1,1,marketingSpendPeriod[0].Marketing_campaign__c,marketingSpendPeriod[0].Id);
        Test.startTest();
        String processed = CS_CostSystem_Controller.CalculateSpendPerLead(marketingSpendPeriod[0].Id);
        Test.stopTest();
        System.assertEquals('Total 1 leads processed and each one costs 1000.00', processed);
    }

    @isTest
    private static void ReprocessUnprocessedLeads_Test(){
        List<Marketing_Campaign__c> marketCampaigns = DFJ_TestDataFactory.CreateMarketCampaigns(1);
        CS_Utility.ProcessPeriod processPeriodInstance = new CS_Utility.ProcessPeriod();
        processPeriodInstance.fromDate = System.now().addDays(-1);
        processPeriodInstance.toDate = System.now().addDays(1);
        Test.startTest();
        CS_CostSystem_Controller.ReprocessUnprocessedLeads(marketCampaigns[0].Id,JSON.serialize(processPeriodInstance));
        Test.stopTest();
    }
    
    @isTest
    private static void CreateCostLedgerForUnprocessedLeads_Test(){
        List<Marketing_Spend_Period__c> marketingSpendPeriod = DFJ_TestDataFactory.CreateMarketCampaignsWithSpendPeriod(1,1);
        List<Lead> leadList = DFJ_TestDataFactory.CreateleadWithLedger(1,1,marketingSpendPeriod[0].Marketing_campaign__c,marketingSpendPeriod[0].Id);
        List<Cost_Ledger__c> ledgerList = [SELECT Id,Name,Lead__c,Marketing_campaign__c,Marketing_Spend__c,Cost_type__c,Amount_of_cost__c,Time_of_cost__c FROM Cost_Ledger__c];
        List<Cost_Ledger__c> ledgerList2 = new List<Cost_Ledger__c>();
        ledgerList2.add(new Cost_Ledger__c(Lead__c=leadList[0].Id));
        Test.startTest();
        String processed = CS_CostSystem_Controller.CreateCostLedgerForUnprocessedLeads(JSON.serialize(ledgerList2), JSON.serialize(leadList));
        String processed2 = CS_CostSystem_Controller.CreateCostLedgerForUnprocessedLeads(JSON.serialize(ledgerList), JSON.serialize(leadList));
        Test.stopTest();
        System.assertEquals('Processed the leads successfully', processed);
        System.assertEquals('Something went wrong.', processed2);
    }

    @isTest
    private static void CreateCostLedgerForUnprocessedLeads2_Test(){
        List<Marketing_Campaign__c> marketingcampaign = DFJ_TestDataFactory.CreateSpendWithMarketingCampaign(1,1);
        List<Lead> leadList = DFJ_TestDataFactory.CreateleadWithLedger(1,1,'','');
        List<Cost_Ledger__c> ledgerList = [SELECT Id,Name,Lead__c,Marketing_campaign__c,Marketing_Spend__c,Cost_type__c,Amount_of_cost__c,Time_of_cost__c FROM Cost_Ledger__c];
        CS_Utility.ProcessPeriod processPeriodInstance = new CS_Utility.ProcessPeriod();
        processPeriodInstance.fromDate = System.now().addDays(-1);
        processPeriodInstance.toDate = System.now().addDays(1);
        Test.startTest();
        CS_CostSystem_Controller.LeadSpendPeriodWrapper processed = CS_CostSystem_Controller.ReprocessUnprocessedLeads(marketingcampaign[0].Id, JSON.serialize(processPeriodInstance) );
        Test.stopTest();
        System.assertEquals('success', processed.message);
    }

    @isTest
    static void FetchMarketingCampaignBySendingEmpty() {
        Test.startTest();
        List<Marketing_Campaign__c> success = CS_Utility.FetchMarketingCampaign(null);
        List<Marketing_Campaign__c> success3 = CS_Utility.FetchRecordsByQuery('',null,'','');
        List<Marketing_Campaign__c> success2 = CS_Utility.FetchMarketingCampaign(new List<String>());
        Test.stopTest();
        System.assertEquals(null, success);
        System.assertEquals(null, success2);
        System.assertEquals(null, success3);
    }

    

    @isTest
    static void CreateMarketSpendPeriodWithEmpty() {
        Test.startTest();
        String query = CS_Selector.FetchMarketingSpendPeriod(null,'','');
        String query2 = CS_Selector.FetchMarketingSpendPeriod(new List<String>(),'','');
        Test.stopTest();
        System.assertEquals(null, query);
        System.assertEquals(null, query2);
    }

    @isTest
    static void CreateLeadWithEmptyFieldsList() {
        Test.startTest();
        String query = CS_Selector.FetchLeadsQuery(null,'','');
        String query2 = CS_Selector.FetchLeadsQuery(new List<String>(),'','');
        Test.stopTest();
        System.assertEquals(null, query);
        System.assertEquals(null, query2);
    }

    @isTest
    static void UpdateCampaignWithUpdatedPeriods() {
        List<Marketing_Campaign__c> marketingcampaign = DFJ_TestDataFactory.CreateSpendWithMarketingCampaign(1,1);
        List <Marketing_Spend_Period__c> spendpPeriodList = [SELECT Id,Name FROM Marketing_Spend_Period__c LIMIT 10];
        Test.startTest();
        CS_CostSystem_Controller.CampaignWrapper CampaignWrapperInstance = CS_CostSystem_Controller.UpdateCampaignWithUpdatedPeriods('', '', '');
        CS_CostSystem_Controller.CampaignWrapper CampaignWrapperInstance3 = CS_CostSystem_Controller.UpdateCampaignWithUpdatedPeriods(JSON.serialize(marketingcampaign[0]), JSON.serialize(spendpPeriodList), '');
        Test.stopTest();
        System.assertEquals(null, CampaignWrapperInstance);

    }

    @isTest
    static void DeleteSpendPeriodWhilUpdatingCampaign() {
        List<Marketing_Campaign__c> marketingcampaign = DFJ_TestDataFactory.CreateSpendWithMarketingCampaign(1,1);
        List <Marketing_Spend_Period__c> spendpPeriodList = [SELECT Id,Name FROM Marketing_Spend_Period__c LIMIT 1];
        Test.startTest();
        CS_CostSystem_Controller.CampaignWrapper CampaignWrapperInstance3 = CS_CostSystem_Controller.UpdateCampaignWithUpdatedPeriods(JSON.serialize(marketingcampaign[0]), '',JSON.serialize(spendpPeriodList));
        Test.stopTest();
        List <Marketing_Spend_Period__c> spendpPeriodToConfirm = [SELECT Id,Name FROM Marketing_Spend_Period__c LIMIT 10];
        System.assertEquals(0, spendpPeriodToConfirm.size());

    }
    
    @isTest
    static void UpdateMarketingCampaignWillAllRelatedSpends() {

        Test.startTest();
        String query = CS_Selector.FetchAccountQuery(null,'','');
        String query2 = CS_Selector.FetchAccountQuery(new List<String>(),'','');
        Test.stopTest();
        System.assertEquals(null, query);
        System.assertEquals(null, query2);

    }

    @isTest
    static void UtilityCodeCoverage() {

        Test.startTest();
        String query = CS_Utility.QueryToFetchAccount('asdf', '');
        String query1 = CS_Utility.QueryToFetchLeads('asdf', '');
        String query2 = CS_Utility.QueryToFetchSpendPeriod('asdf', '');
        Test.stopTest();
        System.assertEquals(null, query);
        System.assertEquals(null, query1);
        System.assertEquals(null, query2);

    }
}