force-app/main/default/objects/Campaign/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host</label>
    <referenceTo>Hosts__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Related_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Event_ID__c</fullName>
    <externalId>true</externalId>
    <label>Related Event ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Campaign/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Related_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Event_ID__c</fullName>
    <label>Related Event ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host</label>
    <referenceTo>Hosts__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hosts__c/Hosts__c.object-meta.xml
<CustomObject>
    <label>Host</label>
    <nameField>
        <label>Host</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hosts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hosts__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hosts</relationshipLabel>
    <relationshipName>Hosts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hosts__c/fields/Default_Invoicing_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Default_Invoicing_Agreement__c</fullName>
    <label>Default Invoicing Agreement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoicing_Agreement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hosts__c/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Provider_id__c.field-meta.xml
<CustomField>
    <fullName>Provider_id__c</fullName>
    <externalId>true</externalId>
    <label>Provider ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Related_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Event_ID__c</fullName>
    <label>Related Event ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Invoicing_Agreement.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Per Booked Seat</fullName>
    </customValue>
    <customValue>
        <fullName>Per Scanned Attendee</fullName>
    </customValue>
    <customValue>
        <fullName>Locked-In Booking Count</fullName>
    </customValue>
    <customValue>
        <fullName>Venue Rental Cost</fullName>
    </customValue>
    <customValue>
        <fullName>No Invoicing</fullName>
    </customValue>
    <masterLabel>Invoicing Agreement</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DFJ_DK</fullName>
        <default>true</default>
        <label>Din Familie Jurist</label>
    </customValue>
    <customValue>
        <fullName>FA_SE</fullName>
        <label>dinfamiliejurist.nu</label>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Testamente_SV</fullName>
        <isActive>false</isActive>
        <label>Testamente Sverige</label>
    </customValue>
    <customValue>
        <fullName>Testamente_DK</fullName>
        <isActive>false</isActive>
        <label>Testamente Danmark</label>
    </customValue>
    <masterLabel>Market Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DFJ_HandleEventCampaignStatusTest.cls
@isTest
public class DFJ_HandleEventCampaignStatusTest {
    @TestSetup
    static void createTestData() {
        
        Contact conRecord = new Contact();
        conRecord.LastName = 'TestContact';
        insert conRecord;
           
        Hosts__c hostInst = new Hosts__c();
        hostInst.Name = 'Test Host';
        hostInst.Country__c = 'testCountry';
        hostInst.Contact__c = conRecord.Id;
        hostInst.Default_Invoicing_Agreement__c = 'Per Booked Seat';
        hostInst.Market_Unit__c = 'Testamente_DK';
        insert hostInst;
        
        Campaign campInst = new Campaign();
        campInst.Status = 'In Progress';
        campInst.Name = 'Test Camp';
        campInst.Start__c = System.now();
        campInst.Related_Event_ID__c = '1234caTest';
        campInst.Market_Unit__c = 'Testamente_DK';
        campInst.Host__c = hostInst.Id;
        insert campInst;
        
        Lead leadInst = new Lead();
        leadInst.provider_Id__c = 'testId';
        leadInst.LastName = 'TestLeadName';
		leadInst.Related_Event_ID__c =  '1234caTest';    
        insert leadInst;
        
        Event eventInst = new Event();
        eventInst.ActivityDateTime = DateTime.now();
        eventInst.DurationInMinutes = 12;
        eventInst.Related_Event_ID__c = '1234caTest';
        insert eventInst;
        
 		/*CampaignMember campMemberInst= new CampaignMember();
        campMemberInst.campaignId = campInst.Id;
        campMemberInst.leadId = leadInst.Id;
        insert campMemberInst;
        system.debug('campMemberInst-->'+campMemberInst);*/
    }
    
    @isTest
    private static void handleCancelEvent_Test(){
        DFJ_HandleEventCampaignStatus.selectedInputWrapper testWrapper = new DFJ_HandleEventCampaignStatus.selectedInputWrapper();
        testWrapper.noReason=false;
        List<Campaign> campList = [SELECT Id FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];
        Test.startTest();
        DFJ_HandleEventCampaignStatus.handleCancelEvent(campList[0].Id,testWrapper);
        Test.stopTest();
        List<Campaign> campList2 = [SELECT Id,Status FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];
		System.assertEquals('Cancelled', campList2[0].Status);
    }
    //DFJ-159 Changes
    @isTest
    private static void handleCancelEvent_Test2(){
        DFJ_HandleEventCampaignStatus.selectedInputWrapper testWrapper = new DFJ_HandleEventCampaignStatus.selectedInputWrapper();
        testWrapper.reasonFromPickList='Too few bookings';
        List<Campaign> campList = [SELECT Id FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];
        Test.startTest();
        DFJ_HandleEventCampaignStatus.handleCancelEvent(campList[0].Id,testWrapper);
        Test.stopTest();
        List<Campaign> campList2 = [SELECT Id,Status FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];
		System.assertEquals('Cancelled', campList2[0].Status);
    }
    @isTest
    private static void handleCancelEvent_Test3(){
        DFJ_HandleEventCampaignStatus.selectedInputWrapper testWrapper = new DFJ_HandleEventCampaignStatus.selectedInputWrapper();
        testWrapper.reasonFromPickList='Illness';
        List<Campaign> campList = [SELECT Id FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];
        Test.startTest();
        DFJ_HandleEventCampaignStatus.handleCancelEvent(campList[0].Id,testWrapper);
        Test.stopTest();
        List<Campaign> campList2 = [SELECT Id,Status FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];
		System.assertEquals('Cancelled', campList2[0].Status);
    }
   //End 
    @isTest
    private static void handleRescheduleEvent_Test(){
         DFJ_HandleEventCampaignStatus.selectedInputWrapper testWrapper = new DFJ_HandleEventCampaignStatus.selectedInputWrapper();
        testWrapper.reasonFromPickList='Too few bookings';
        List<Campaign> campList = [SELECT Id FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];
        String dateTimeString = '2023-10-10 00:45:00.000';
        Test.startTest();
        DFJ_HandleEventCampaignStatus.handleRescheduleEvent(campList[0].Id,dateTimeString,testWrapper);
        Test.stopTest();
        List<Event> eventList2 = [SELECT Id,Event_Status__c FROM Event WHERE Related_Event_ID__c = '1234caTest'];
		System.assertEquals('Rescheduled', eventList2[0].Event_Status__c);
    }
     @isTest
    private static void handleRescheduleEvent_Test2(){
         DFJ_HandleEventCampaignStatus.selectedInputWrapper testWrapper = new DFJ_HandleEventCampaignStatus.selectedInputWrapper();
        testWrapper.reasonFromPickList='Illness';
        List<Campaign> campList = [SELECT Id FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];
        String dateTimeString = '2023-10-10 00:45:00.000';
        Test.startTest();
        DFJ_HandleEventCampaignStatus.handleRescheduleEvent(campList[0].Id,dateTimeString,testWrapper);
        Test.stopTest();
        List<Event> eventList2 = [SELECT Id,Event_Status__c FROM Event WHERE Related_Event_ID__c = '1234caTest'];
		System.assertEquals('Rescheduled', eventList2[0].Event_Status__c);
    }
    
    @isTest
    private static void getAllHosts_Test(){
        Test.startTest();
        DFJ_HandleEventCampaignStatus.getAllHosts();
        Test.stopTest();
        List<Hosts__c> getAllHostList= [SELECT Id,Name FROM Hosts__c];
        System.assertEquals(1, getAllHostList.size());

    }
    
    @isTest
    private static void hostLocationChange_Test(){
        DFJ_HandleEventCampaignStatus.selectedInputWrapper testWrapper = new DFJ_HandleEventCampaignStatus.selectedInputWrapper();
        testWrapper.reasonFromPickList='Too few bookings';
        List<Hosts__c> hostList = [SELECT Id,Name FROM Hosts__c WHERE Name='Test Host'];
        List<Campaign> campList = [SELECT Id,Start__c FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];

        Test.startTest();
        DFJ_HandleEventCampaignStatus.hostLocationChange(campList[0].Id, hostList[0].Id,testWrapper);
        Test.stopTest();
        List<Hosts__c> getAllHostList= [SELECT Id FROM Hosts__c WHERE Name ='Test Host' ];
        List<Campaign> campList2 = [SELECT Id,Host__c FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];
        System.assertEquals(campList2[0].Host__c, getAllHostList[0].Id);
    }
     @isTest
    private static void hostLocationChange_Test2(){
        DFJ_HandleEventCampaignStatus.selectedInputWrapper testWrapper = new DFJ_HandleEventCampaignStatus.selectedInputWrapper();
        testWrapper.reasonFromPickList='Illness';
        List<Hosts__c> hostList = [SELECT Id,Name FROM Hosts__c WHERE Name='Test Host'];
        List<Campaign> campList = [SELECT Id,Start__c FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];

        Test.startTest();
        DFJ_HandleEventCampaignStatus.hostLocationChange(campList[0].Id, hostList[0].Id,testWrapper);
        Test.stopTest();
        List<Hosts__c> getAllHostList= [SELECT Id FROM Hosts__c WHERE Name ='Test Host' ];
        List<Campaign> campList2 = [SELECT Id,Host__c FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];
        System.assertEquals(campList2[0].Host__c, getAllHostList[0].Id);
    }
    @isTest
    private static void getCurrentHostsEmail_Test(){
        List<Campaign> campList = [SELECT Id,Start__c FROM Campaign WHERE Related_Event_ID__c = '1234caTest'];

        Test.startTest();
        DFJ_HandleEventCampaignStatus.getCurrentHostsEmail(campList[0].Id);
        Test.stopTest();
        
    }
    
  
}