force-app/main/default/objects/Account/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payments</label>
    <referenceTo>Payments__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Journals</relationshipLabel>
    <relationshipName>Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Journals</relationshipLabel>
    <relationshipName>Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Inheritance</fullName>
                <default>true</default>
                <label>Inheritance</label>
            </value>
            <value>
                <fullName>Admin of estate</fullName>
                <label>Bobehandling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payments</label>
    <referenceTo>Payments__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Provider_id__c.field-meta.xml
<CustomField>
    <fullName>Provider_id__c</fullName>
    <externalId>true</externalId>
    <label>Provider ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Related_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Event_ID__c</fullName>
    <label>Related Event ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/DFJ_DK.recordType-meta.xml
<RecordType>
    <fullName>DFJ_DK</fullName>
    <active>true</active>
    <businessProcess>Process To distribute leads</businessProcess>
    <label>Denmark</label>
</RecordType>

force-app/main/default/objects/Order/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Fixed_discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Fixed_discount_Type__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fixed Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payments</label>
    <referenceTo>Payments__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Provision_Base__c.field-meta.xml
<CustomField>
    <fullName>Provision_Base__c</fullName>
    <description>Summation of all related order product Provision Base value</description>
    <label>Provision Base</label>
    <summarizedField>OrderItem.Provision_base__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Related_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Event_ID__c</fullName>
    <label>Related Event ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_order_line__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_order_line__c/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payments</label>
    <referenceTo>Payments__c</referenceTo>
    <relationshipLabel>Payment order lines</relationshipLabel>
    <relationshipName>Payment_order_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_order_line__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Payment order lines</relationshipLabel>
    <relationshipName>Payment_order_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_order_line__c/fields/Provision_base__c.field-meta.xml
<CustomField>
    <fullName>Provision_base__c</fullName>
    <label>Provision base</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_order_line__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/IsInsertOrder__c.field-meta.xml
<CustomField>
    <fullName>IsInsertOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsInsertOrder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Draft - Bobehandling</fullName>
            </value>
            <value>
                <fullName>Cancellation mail sent</fullName>
            </value>
            <value>
                <fullName>Cancellation advisor responsible</fullName>
            </value>
            <value>
                <fullName>Cancellation management responsible</fullName>
            </value>
            <value>
                <fullName>Canceled – Refund</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Followup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Pricebook2Id__c.field-meta.xml
<CustomField>
    <fullName>Pricebook2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Dunning</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Authorized</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onetime</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Market_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DFJ_DK</fullName>
        <default>true</default>
        <label>Din Familie Jurist</label>
    </customValue>
    <customValue>
        <fullName>FA_SE</fullName>
        <label>dinfamiliejurist.nu</label>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Testamente_SV</fullName>
        <isActive>false</isActive>
        <label>Testamente Sverige</label>
    </customValue>
    <customValue>
        <fullName>Testamente_DK</fullName>
        <isActive>false</isActive>
        <label>Testamente Danmark</label>
    </customValue>
    <masterLabel>Market Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentsTriggerHandlerTest.cls
@IsTest 
public class PaymentsTriggerHandlerTest {
    
    
    @isTest
    private static void createOrderAndOrderItem_Test1(){
        try{
            
            Product2 pro = new Product2(Name = 'iPhone X', Family = 'Mobile');
        Insert pro;
        Pricebook2 standardPricebook = new Pricebook2( Id = Test.getStandardPricebookId(), IsActive = true);
        Update standardPricebook;
        
        
        
        //Create the PricebookEntry
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = pro.Id,
            UnitPrice = 1020,
            IsActive = true
        );
        Insert pbe;
     Lead testLead = new Lead(Company='Test Lead',FirstName='John',LastName='Doe',Provider_id__c = '1324');
            insert testLead;
            Account accInst = new Account();
            accInst.Name = 'test Acc';
            accInst.Lead__c = testLead.Id;
            insert accInst;
            
            Journal__c journalInstance = new Journal__c();
            journalInstance.External_record_uuid__c = 'test';
            journalInstance.Lead__c = testLead.Id;
            journalInstance.Account__c = accInst.id;
            insert journalInstance;
            
            Payments__c paymentRecord = new Payments__c();
            paymentRecord.Account__c = accInst.id;
            paymentRecord.Type__c = 'Onetime';
            paymentRecord.Amount__c =  100 ;
            paymentRecord.CurrencyIsoCode =  'DKK' ;
            paymentRecord.Pricebook2Id__c = standardPricebook.Id;
            paymentRecord.Lead__c = testLead.Id;
            paymentRecord.Order_Status__c = 'Draft';
            paymentRecord.Market_Unit__c = 'DFJ_DK';
            paymentRecord.Related_Event_ID__c = '' ;
            paymentRecord.Fixed_discount_Type__c = 10 ;
            paymentRecord.Campaign__c = null ;
            paymentRecord.isInsertOrder__c = true ;
            paymentRecord.Journal__c = null ;
            paymentRecord.Status__c = 'Pending' ;
            paymentRecord.IsInsertOrder__c = true;
            paymentRecord.BillingCountry__c = 'DK';
            paymentRecord.Billing_name__c = accInst.Name;
            paymentRecord.Billing_email__c = 'test@test.com';
            insert paymentRecord;
            
            Payment_order_line__c paymentOrderItem = new Payment_order_line__c();
            //for OrderItems
            paymentOrderItem.Provision_base__c = 0;
            paymentOrderItem.Discount__c = 10;
            paymentOrderItem.UnitPrice__c = 100;
            paymentOrderItem.Product2Id__c = pro.Id;
            paymentOrderItem.PricebookEntryId__c = pbe.Id;
            paymentOrderItem.CurrencyIsoCode = 'DKK';
            //End
            paymentOrderItem.Amount__c = 20; 
            paymentOrderItem.Quantity__c = 1;
            paymentOrderItem.Vat__c = 0;
            paymentOrderItem.Name = 'Test';
            paymentOrderItem.Payments__c = paymentRecord.Id;
            insert paymentOrderItem;
            Payments__c updatepaymentRecord = new Payments__c();
            updatepaymentRecord.Id =   paymentRecord.Id;
            updatepaymentRecord.Status__c = 'Settled';
            update  updatepaymentRecord;
            

            List<Order> orderList = [SELECT Id FROM Order WHERE Payments__c =:paymentRecord.id];
            System.assertEquals(1, orderList.size());
            //System.debug('journalList-->'+journalList);
        }catch(exception ex){
            System.debug('error message--> '+ ex.getmessage()+ '--InLine --->'+ex.getlinenumber());
        }
    }
    
    @isTest
    private static void createOrderAndOrderItem_Test2(){
        try{
            
            
             Product2 pro = new Product2(Name = 'iPhone X', Family = 'Mobile');
        Insert pro;
        Pricebook2 standardPricebook = new Pricebook2( Id = Test.getStandardPricebookId(), IsActive = true);
        Update standardPricebook;
        
        
        
        //Create the PricebookEntry
        PricebookEntry pbe = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = pro.Id,
            UnitPrice = 1020,
            IsActive = true
        );
        Insert pbe;
           
            
            
            Lead testLead = new Lead(Company='Test Lead',FirstName='John',LastName='Doe',Provider_id__c = '1324');
            insert testLead;
            Account accInst = new Account();
            accInst.Name = 'test Acc';
            accInst.Lead__c = testLead.Id;
            insert accInst;
            
            Journal__c journalInstance = new Journal__c();
            journalInstance.External_record_uuid__c = 'test';
            journalInstance.Lead__c = testLead.Id;
            journalInstance.Account__c = accInst.id;
            insert journalInstance;
            
            Payments__c paymentRecord = new Payments__c();
            paymentRecord.Account__c = accInst.id;
            paymentRecord.Type__c = 'Onetime';
            paymentRecord.Amount__c =  100 ;
            paymentRecord.CurrencyIsoCode =  'DKK' ;
            paymentRecord.Pricebook2Id__c = standardPricebook.Id;
            paymentRecord.Lead__c = testLead.Id;
            paymentRecord.Order_Status__c = 'Draft';
            paymentRecord.Market_Unit__c = 'DFJ_DK';
            paymentRecord.Related_Event_ID__c = '' ;
            paymentRecord.Fixed_discount_Type__c = 10 ;
            paymentRecord.Campaign__c = null ;
            paymentRecord.isInsertOrder__c = true ;
            paymentRecord.Journal__c = null ;
            paymentRecord.Status__c = 'Pending' ;
            paymentRecord.IsInsertOrder__c = true;
            paymentRecord.BillingCountry__c = 'DK';
            paymentRecord.Billing_name__c = accInst.Name;
            paymentRecord.Billing_email__c = 'test@test.com';
            insert paymentRecord;
            
            Payment_order_line__c paymentOrderItem = new Payment_order_line__c();
            //for OrderItems
            paymentOrderItem.Provision_base__c = 0;
            paymentOrderItem.Discount__c = 10;
            paymentOrderItem.UnitPrice__c = 100;
            paymentOrderItem.Product2Id__c = pro.Id;
            paymentOrderItem.PricebookEntryId__c = pbe.Id;
            paymentOrderItem.CurrencyIsoCode = 'DKK';
            //End
            paymentOrderItem.Amount__c = 20; 
            paymentOrderItem.Quantity__c = 1;
            paymentOrderItem.Vat__c = 0;
            paymentOrderItem.Name = 'Test';
            paymentOrderItem.Payments__c = paymentRecord.Id;
            insert paymentOrderItem;
            Payments__c updatepaymentRecord = new Payments__c();
            updatepaymentRecord.Id =   paymentRecord.Id;
            updatepaymentRecord.Status__c = 'Settled';
            update  updatepaymentRecord;
            
            
            List<Payments__c> paymentList = [SELECT Id,IsInsertOrder__c FROM Payments__c WHERE Id =:paymentRecord.id];
            System.assertEquals(false, paymentList[0].IsInsertOrder__c);
            //System.debug('journalList-->'+journalList);
        }catch(exception ex){
            System.debug('error message--> '+ ex.getmessage()+ '--InLine --->'+ex.getlinenumber());
        }
    }
}