force-app/main/default/objects/Account/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_assistance__c.field-meta.xml
<CustomField>
    <fullName>Legal_assistance__c</fullName>
    <label>Legal assistance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer requested lawyer meeting</fullName>
            </value>
            <value>
                <fullName>Booked Tailored Document meeting</fullName>
            </value>
            <value>
                <fullName>Questions related to generating documents</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Meeting_Type__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Type__c</fullName>
    <label>Meeting Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales meeting</fullName>
            </value>
            <value>
                <fullName>Service call</fullName>
            </value>
            <value>
                <fullName>Legal assistance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_meeting__c.field-meta.xml
<CustomField>
    <fullName>Sales_meeting__c</fullName>
    <label>Sales meeting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ring igen</fullName>
            </value>
            <value>
                <fullName>Intro givet</fullName>
            </value>
            <value>
                <fullName>Fællesmøde</fullName>
            </value>
            <value>
                <fullName>Singlemøde</fullName>
            </value>
            <value>
                <fullName>Fysisk møde</fullName>
            </value>
            <value>
                <fullName>Journal udfyldt / Afventer betaling</fullName>
            </value>
            <value>
                <fullName>Tilbud sendt</fullName>
            </value>
            <value>
                <fullName>Ikke kontaktet</fullName>
            </value>
            <value>
                <fullName>Webmøde</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Send_SMS_Reminders__c.field-meta.xml
<CustomField>
    <fullName>Send_SMS_Reminders__c</fullName>
    <label>Send SMS Reminders</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_call__c.field-meta.xml
<CustomField>
    <fullName>Service_call__c</fullName>
    <label>Service call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Service call</fullName>
            </value>
            <value>
                <fullName>Trustpilot follow-up</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Journals</relationshipLabel>
    <relationshipName>Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DFJ_AppointmentController_Test.cls
@isTest
public with sharing class DFJ_AppointmentController_Test {
    @isTest
    private static void getAppointmentConfigurations_Test(){
        Test.startTest();
        DFJ_AppointmentController_Apex.getAppointmentConfigurations();
        Test.stopTest();
    }

    @isTest
    private static void saveAccountAndEventInformation_Test(){
        Account acc = new Account();
        acc.Name = 'Test';
        insert acc;
        
        String evtData = '{"StartDateTime":"2023-06-29T18:58:00.000Z","Subject":"asas","Journal__c":"","OwnerId":"0051t000002kYspAAE","WhatId":"","EndDateTime":"","Account__c":""}';
        String accData ='{"Id":"'+acc.Id +'","Send_SMS_Reminders__c":"No","Meeting_Type__c":"Sales meeting","Legal_assistance__c":"","Service_call__c":"","Sales_meeting__c":"Ring igen"}';
        Test.startTest();
        DFJ_AppointmentController_Apex.saveAccountAndEventInformation(accData,evtData, acc.Id, 20, '2023-06-29T18:58:00.000Z','00:45:00.000','2023-07-06');
        Test.stopTest();
    }

}