force-app/main/default/objects/Account/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Meeting_Type__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Type__c</fullName>
    <label>Meeting Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales meeting</fullName>
            </value>
            <value>
                <fullName>Service call</fullName>
            </value>
            <value>
                <fullName>Legal assistance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_meeting__c.field-meta.xml
<CustomField>
    <fullName>Sales_meeting__c</fullName>
    <label>Sales meeting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ring igen</fullName>
            </value>
            <value>
                <fullName>Intro givet</fullName>
            </value>
            <value>
                <fullName>Fællesmøde</fullName>
            </value>
            <value>
                <fullName>Singlemøde</fullName>
            </value>
            <value>
                <fullName>Fysisk møde</fullName>
            </value>
            <value>
                <fullName>Journal udfyldt / Afventer betaling</fullName>
            </value>
            <value>
                <fullName>Tilbud sendt</fullName>
            </value>
            <value>
                <fullName>Ikke kontaktet</fullName>
            </value>
            <value>
                <fullName>Webmøde</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Send_SMS_Reminders__c.field-meta.xml
<CustomField>
    <fullName>Send_SMS_Reminders__c</fullName>
    <label>Send SMS Reminders</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Journals</relationshipLabel>
    <relationshipName>Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DFJ_EventController_Test.cls
@isTest
public with sharing class DFJ_EventController_Test {
    @isTest
    private static void getAllEventethod_Test(){
        String accData ='{"Name":"Test","Send_SMS_Reminders__c":"No","Meeting_Type__c":"Sales meeting","Sales_meeting__c":"Ring igen"}';
        Account acc = (Account) JSON.deserialize(accData, Account.class);
        insert acc;

        String evtData = '{"EndDateTime":"2023-06-28T17:58:00.000Z","StartDateTime":"2023-06-28T16:58:00.000Z","Subject":"asas","Journal__c":"","OwnerId":"'+UserInfo.getUserId()+'","WhatId":"'+acc.Id +'","Account__c":"'+acc.Id +'"}';
        Event evt = (Event) JSON.deserialize(evtData, Event.class);
        insert evt;

        Test.startTest();
        DFJ_EventController.getAllEventethod(UserInfo.getUserId(), null, UserInfo.getUserId());
        Test.stopTest();
    }

    @isTest
    private static void getAllRelatedEvents_Test(){
        String accData ='{"Name":"Test","Send_SMS_Reminders__c":"No","Meeting_Type__c":"Sales meeting","Sales_meeting__c":"Ring igen"}';
        Account acc = (Account) JSON.deserialize(accData, Account.class);
        insert acc;

        String evtData = '{"EndDateTime":"2023-06-28T17:58:00.000Z","StartDateTime":"2023-06-28T16:58:00.000Z","Subject":"asas","Journal__c":"","OwnerId":"'+UserInfo.getUserId()+'","WhatId":"'+acc.Id +'","Account__c":"'+acc.Id +'"}';
        Event evt = (Event) JSON.deserialize(evtData, Event.class);
        insert evt;

        Test.startTest();
        DFJ_EventController.getAllRelatedEvents(Datetime.newInstance(2023, 06, 28, 16, 58, 0) ,UserInfo.getUserId());
        Test.stopTest();
    }
}