force-app/main/default/objects/Account/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payments</label>
    <referenceTo>Payments__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Journals</relationshipLabel>
    <relationshipName>Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Journals</relationshipLabel>
    <relationshipName>Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Journals</relationshipLabel>
    <relationshipName>Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Fixed_discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Fixed_discount_Type__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fixed Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payments</label>
    <referenceTo>Payments__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Provision_Base__c.field-meta.xml
<CustomField>
    <fullName>Provision_Base__c</fullName>
    <description>Summation of all related order product Provision Base value</description>
    <label>Provision Base</label>
    <summarizedField>OrderItem.Provision_base__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Related_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Event_ID__c</fullName>
    <label>Related Event ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_order_line__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_order_line__c/fields/Payments__c.field-meta.xml
<CustomField>
    <fullName>Payments__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payments</label>
    <referenceTo>Payments__c</referenceTo>
    <relationshipLabel>Payment order lines</relationshipLabel>
    <relationshipName>Payment_order_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_order_line__c/fields/Product2Id__c.field-meta.xml
<CustomField>
    <fullName>Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Payment order lines</relationshipLabel>
    <relationshipName>Payment_order_lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_order_line__c/fields/Provision_base__c.field-meta.xml
<CustomField>
    <fullName>Provision_base__c</fullName>
    <label>Provision base</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_order_line__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/IsInsertOrder__c.field-meta.xml
<CustomField>
    <fullName>IsInsertOrder__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsInsertOrder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Draft - Bobehandling</fullName>
            </value>
            <value>
                <fullName>Cancellation mail sent</fullName>
            </value>
            <value>
                <fullName>Cancellation advisor responsible</fullName>
            </value>
            <value>
                <fullName>Cancellation management responsible</fullName>
            </value>
            <value>
                <fullName>Canceled – Refund</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Followup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payments__c/fields/Pricebook2Id__c.field-meta.xml
<CustomField>
    <fullName>Pricebook2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Market_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DFJ_DK</fullName>
        <default>true</default>
        <label>Din Familie Jurist</label>
    </customValue>
    <customValue>
        <fullName>FA_SE</fullName>
        <label>dinfamiliejurist.nu</label>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Testamente_SV</fullName>
        <isActive>false</isActive>
        <label>Testamente Sverige</label>
    </customValue>
    <customValue>
        <fullName>Testamente_DK</fullName>
        <isActive>false</isActive>
        <label>Testamente Danmark</label>
    </customValue>
    <masterLabel>Market Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentsTriggerHandler.cls
public class PaymentsTriggerHandler {
    public static void createOrderAndOrderItem(Set<Id> paymentIds){
        try{
            List<Order> insertOrderList = new List<Order>();
            List<Payments__c> updatePaymentList = new List<Payments__c>();
            List<OrderItem> insertOrderItemList = new List<OrderItem>();
            Map<Id,Id> paymentIdVsOrderId = new Map<Id,Id>();
            
            List<Payments__c> getPayments = [SELECT Id, CreatedById,OwnerId, Account__c,Account__r.Lead__c,Order_Status__c,Lead__c,Market_Unit__c,Related_Event_ID__c,Pricebook2Id__c,CurrencyIsoCode,Fixed_discount_Type__c,Campaign__c,Journal__c FROM Payments__c WHERE Id=:paymentIds LIMIT 10000];
            for(Payments__c record: getPayments){
            	Order createOrder = new Order();
                createOrder.Payments__c = record.Id;
                createOrder.Status = !String.isBlank(record.Order_Status__c) ? record.Order_Status__c : '' ;
                createOrder.Market_Unit__c = !String.isBlank(record.Market_Unit__c) ? record.Market_Unit__c : '' ;
                createOrder.AccountId = (record.Account__c != null) ? record.Account__c : null ;
                createOrder.Related_Event_ID__c =  !String.isBlank(record.Related_Event_ID__c) ? record.Related_Event_ID__c : '' ; 
                createOrder.Pricebook2Id = (record.Pricebook2Id__c != null) ? record.Pricebook2Id__c : null ; 
                createOrder.Journal__c = (record.Journal__c != null) ? record.Journal__c : null ; 
                createOrder.CurrencyIsoCode = record.CurrencyIsoCode;
                createOrder.Fixed_discount_Type__c = (record.Fixed_discount_Type__c != null) ? record.Fixed_discount_Type__c : 0 ; 
                createOrder.EffectiveDate = System.Today();
                createOrder.Lead__c = (record.Account__r.Lead__c != null) ? record.Account__r.Lead__c : null ;
                createOrder.Campaign__c = (record.Campaign__c != null) ? record.Campaign__c : null ;
                createOrder.OwnerId = record.OwnerId;
                createOrder.CreatedById = record.CreatedById;
                insertOrderList.add(createOrder);
        	}
            

            
            if(!insertOrderList.isEmpty()){
                 insert insertOrderList;
                for(Order record:insertOrderList){
                    if(!paymentIdVsOrderId.containskey(record.Payments__c)){
                        paymentIdVsOrderId.put(record.Payments__c,record.Id);
                    }
                    Payments__c paymentRecord = new Payments__c();
                    paymentRecord.Id = record.Payments__c;
                    paymentRecord.Order__c = record.Id;
                    paymentRecord.isInsertOrder__c = false;
                    updatePaymentList.add(paymentRecord);
                }
            } 
            if(!insertOrderList.isEmpty()){
                List<Payment_order_line__c> getPaymentOrderLines = [SELECT Id,CreatedById,Name,Payments__c,Quantity__c,Payments__r.Pricebook2Id__c,PricebookEntryId__c,Product2Id__c,Discount__c,UnitPrice__c,Provision_base__c FROM Payment_order_line__c WHERE Payments__c=:paymentIds LIMIT 10000];
                for(Payment_order_line__c record: getPaymentOrderLines){
                	OrderItem createOrderItem = new OrderItem();
                	createOrderItem.OrderId = paymentIdVsOrderId.get(record.Payments__c);
                	createOrderItem.Discount__c = (record.Discount__c != null) ? record.Discount__c : null ;
                	createOrderItem.PricebookEntryId = (record.PricebookEntryId__c != null) ? record.PricebookEntryId__c : null ;
               		createOrderItem.Product2Id = (record.Product2Id__c != null) ? record.Product2Id__c : null ; 
                	createOrderItem.Quantity = (record.Quantity__c != null) ? record.Quantity__c : 0 ;
                	createOrderItem.UnitPrice =  (record.UnitPrice__c != null) ? record.UnitPrice__c : 0 ; 
                	createOrderItem.Product2Id = (record.Product2Id__c != null) ? record.Product2Id__c : null ; 
                    createOrderItem.CreatedById = record.CreatedById;
                
                	insertOrderItemList.add(createOrderItem);
            	}
                
            }
            
            
            
            if(!insertOrderItemList.isEmpty()){
                 insert insertOrderItemList;
            }
            if(!updatePaymentList.isEmpty()){
                 update updatePaymentList;
            }
            
            
            
            }catch(Exception ex){
        DFJ_ErrorLogController.addErrorLogs('', 'Error while creating Order and OrderItems on payment Settled record', ex.getMessage(), 'Error', 'PaymentsTriggerHandler.createOrderAndOrderItem', '', String.valueOf(ex.getLineNumber()));
    }
    }

}