force-app/main/default/objects/Account/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Google_Auth__c/Google_Auth__c.object-meta.xml
<CustomObject>
    <label>Google Auth</label>
    <nameField>
        <label>Google Auth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Auths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Google_Auth__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Google_Auth__c/fields/Token_Name__c.field-meta.xml
<CustomField>
    <fullName>Token_Name__c</fullName>
    <label>Token Name</label>
    <type>TextArea</type>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Journals</relationshipLabel>
    <relationshipName>Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GoogleEventHandlerTest.cls
@isTest
public class GoogleEventHandlerTest {

    @testSetup
    private static void setupTestData() {
        Google_Auth__c auth = new Google_Auth__c(
            Token_Name__c = 'Latest',
            Access_Token__c = 'TestAccessToken'
        );
        insert auth;


        // Insert test ContentVersion records
        List<ContentVersion> contentVersions = new List<ContentVersion>();
        contentVersions.add(new ContentVersion(
            Title = 'Mock File',
            PathOnClient = 'mockFile.txt',
            VersionData = Blob.valueOf('mock file content'),
            Google_Drive_Id__c = 'mock-file-id12'
        ));
        insert contentVersions;

        Account acc = new Account(LastName = 'Test acc');
        insert acc;
        // Insert test Journal__c records
        List<Journal__c> journals = new List<Journal__c>();
        journals.add(new Journal__c(
            Account__c = acc.id
        ));
        insert journals;
    }
    
    @isTest
    public static void TestingMainMethods(){
        
        Blob fileContent = blob.valueof('This is BLob');
        String accessToken = GoogleAPIMethods.getLatestAccessToken();
        Journal__c Journal = [SELECT id, Account__c FROM Journal__c LIMIT 1];
        ContentVersion contentVersion = new ContentVersion();
                        contentVersion.Title = 'Title';
                        contentVersion.PathOnClient = '\Filaname';
                        contentVersion.FirstPublishLocationId = Journal.Id;
                        contentVersion.VersionData = fileContent;
                        contentVersion.Google_Drive_Id__c = 'fileId';
        insert contentVersion;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        GoogleEventHandler.MainLogic();
        
     //   GoogleEventHandler.AttachFile(contentVersion.Id, Journal.Id);
        
        Test.stopTest();
    }
}