force-app/main/default/objects/Account/fields/UTM_Campaign__c.field-meta.xml
<CustomField>
    <fullName>UTM_Campaign__c</fullName>
    <label>UTM Campaign</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gratis raadgivning</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/UTM_Content__c.field-meta.xml
<CustomField>
    <fullName>UTM_Content__c</fullName>
    <label>UTM Content (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>-</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/UTM_Medium__c.field-meta.xml
<CustomField>
    <fullName>UTM_Medium__c</fullName>
    <label>UTM Medium</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Totalliv</fullName>
            </value>
            <value>
                <fullName>Leadad</fullName>
            </value>
            <value>
                <fullName>PR Leads</fullName>
            </value>
            <value>
                <fullName>Billetto</fullName>
            </value>
            <value>
                <fullName>Tilmeldingsblanket</fullName>
            </value>
            <value>
                <fullName>Calendly</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Andet</fullName>
            </value>
            <value>
                <fullName>Popermo</fullName>
            </value>
            <value>
                <fullName>Meet the Team</fullName>
            </value>
            <value>
                <fullName>Website Form</fullName>
            </value>
            <value>
                <fullName>Salesforce Screen Flow</fullName>
            </value>
            <value>
                <fullName>1 timmars gratis raadgivning</fullName>
            </value>
            <value>
                <fullName>Findforsikring.dk</fullName>
            </value>
            <value>
                <fullName>Registration Form Invite</fullName>
            </value>
            <value>
                <fullName>Marketing Email</fullName>
            </value>
            <value>
                <fullName>Personal Link</fullName>
            </value>
            <value>
                <fullName>Kundkontakter</fullName>
            </value>
            <value>
                <fullName>Outgrow</fullName>
            </value>
            <value>
                <fullName>Seren</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Gratis raadgivning</fullName>
            </value>
            <value>
                <fullName>Cube</fullName>
            </value>
            <value>
                <fullName>Google-ads</fullName>
            </value>
            <value>
                <fullName>eGentic</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>eGentic/Premio</fullName>
            </value>
            <value>
                <fullName>Contact Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/UTM_Source__c.field-meta.xml
<CustomField>
    <fullName>UTM_Source__c</fullName>
    <label>UTM Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Foredrag</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Selvoprettet</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
            <value>
                <fullName>Imported</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Danish Website</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Internal Meeting Booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/UTM_Term__c.field-meta.xml
<CustomField>
    <fullName>UTM_Term__c</fullName>
    <label>UTM Term</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3 procent lookalike af alle leads, gift og samlevende</fullName>
            </value>
            <value>
                <fullName>Pre-booking</fullName>
            </value>
            <value>
                <fullName>PR leads - Gifte m. dine og mine børn</fullName>
            </value>
            <value>
                <fullName>DK - Website Form</fullName>
            </value>
            <value>
                <fullName>dk_gifte_forældre</fullName>
            </value>
            <value>
                <fullName>Gifte m. dine og mine børn</fullName>
            </value>
            <value>
                <fullName>Sambo m. børn</fullName>
            </value>
            <value>
                <fullName>PR Lead Internal Meeting Booking</fullName>
            </value>
            <value>
                <fullName>A1 København + århus + vejle</fullName>
            </value>
            <value>
                <fullName>Juridisk rådgivning - vi ringer til dig med link til kalender</fullName>
            </value>
            <value>
                <fullName>all</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/UTM_Content__c.field-meta.xml
<CustomField>
    <fullName>UTM_Content__c</fullName>
    <label>UTM Content</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Campaign</label>
    <referenceTo>Marketing_Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UTM_Campaign__c.field-meta.xml
<CustomField>
    <fullName>UTM_Campaign__c</fullName>
    <label>UTM Campaign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UTM_Campaign</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/UTM_Content__c.field-meta.xml
<CustomField>
    <fullName>UTM_Content__c</fullName>
    <label>UTM Content (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Vil gerne oprette et testamente</fullName>
            </value>
            <value>
                <fullName>Tilbud på en bobestyrer</fullName>
            </value>
            <value>
                <fullName>Bestilt Fremtidsfuldmagt for 145,- inkl. juridisk rådgivning</fullName>
            </value>
            <value>
                <fullName>Bobehandling</fullName>
            </value>
            <value>
                <fullName>Gratis fremtidsfuldmagt</fullName>
            </value>
            <value>
                <fullName>Bestilt Børnetestamente for 295,- inkl. juridisk rådgivning</fullName>
            </value>
            <value>
                <fullName>Upprätta en framtidsfullmakt för endast 145:-  inkl. gratis juridisk rådgivning.</fullName>
            </value>
            <value>
                <fullName>Online foredrag med Michael Jepsen</fullName>
            </value>
            <value>
                <fullName>Gratis online foredrag - Sådan sikrer du dig selv og din familie ved sygdom og død</fullName>
            </value>
            <value>
                <fullName>Gratis Testamente foredrag med lækker tapas i Hellerup Sejlklub</fullName>
            </value>
            <value>
                <fullName>Gratis Testamente foredrag med lækker Tapas på Susets Køkken i Hvidovre - ( Afholdt den 29.03.2022 16:00 )</fullName>
            </value>
            <value>
                <fullName>Gratis Testamente foredrag med lækker Stjerneskud på Gerlev Kro i Jægerspris - ( Afholdt den 30.03.2022 16:00 )</fullName>
            </value>
            <value>
                <fullName>Gratis foredrag om Arv &amp; Testamente med lækker anretning på Haarby kro - ( Afholdt den 30.03.2022 16:00 )</fullName>
            </value>
            <value>
                <fullName>Tilmeld gratis foredrag eller 1til1 moede med raadgiver</fullName>
            </value>
            <value>
                <fullName>Tilmeld gratis foredrag eller 1til1 moede med raadgiver med video</fullName>
            </value>
            <value>
                <fullName>Anmäl dig till en kostnadsfri föreläsning eller 1-till-1-möte med en rådgivare</fullName>
            </value>
            <value>
                <fullName>Gratis foredrag om arv og testamente - Kalundborg Senior Forening - 29-10-2022</fullName>
            </value>
            <value>
                <fullName>Gratis föreläsning om arv &amp; testamente. Få svar på hur du säkrar dig och din familj vid sjukdom och dödsfall. - ( Afholdt den 2022-11-14 )</fullName>
            </value>
            <value>
                <fullName>Gratis föreläsning om arv &amp; testamente. Få svar på hur du säkrar dig och din familj vid sjukdom och dödsfall. - ( Afholdt den 2022-10-10 )</fullName>
            </value>
            <value>
                <fullName>Gratis föreläsning om arv &amp; testamente. Få svar på hur du säkrar dig och din familj vid sjukdom och dödsfall. - ( Afholdt den 2022-11-07 )</fullName>
            </value>
            <value>
                <fullName>Gratis föreläsning om arv och testamente inkl. Mat på vartereterikstorp (Afholdt den 2022-04-07 16:00)</fullName>
            </value>
            <value>
                <fullName>Lomma</fullName>
            </value>
            <value>
                <fullName>Gratis foredrag om arv og testamente inkl. middag på Restaurant Fregatten i Greve - ( afholdt d. 10-01-2023 )</fullName>
            </value>
            <value>
                <fullName>Gratis foredrag om arv og testamente inkl. middag på Stubbæk Forsamlingshus i Aabenraa - ( afholdt d. 16-01-2023 )</fullName>
            </value>
            <value>
                <fullName>Gratis foredrag om arv &amp; testamente med lækker Tapas på Rold Skov Golfklub  i Skørping  - ( Afholdt den 2023-01-17 )</fullName>
            </value>
            <value>
                <fullName>Gratis Testamente foredrag med Stegt Flæsk på Nillers Kro i  Sabro - ( Afholdt den 2023-01-09 )</fullName>
            </value>
            <value>
                <fullName>Gratis foredrag om arv &amp; testamente med lækkert luksus smørrebrød på Stubbæk Forsamlingshus i Aabenraa - ( Afholdt den 2023-01-16 )</fullName>
            </value>
            <value>
                <fullName>Gratis Testamente foredrag med lækker Dagens ret  på Herning Golf Cafe - ( Afholdt den 2023-01-17 )</fullName>
            </value>
            <value>
                <fullName>Gratis foredrag om arv og testamente inkl. middag på Restaurant Kareten i København S - ( Afholdt d. 07-02-2023 )</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/UTM_Medium__c.field-meta.xml
<CustomField>
    <fullName>UTM_Medium__c</fullName>
    <label>UTM Medium</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UTM_Medium</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/UTM_Source__c.field-meta.xml
<CustomField>
    <fullName>UTM_Source__c</fullName>
    <label>UTM Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UTM_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/UTM_Term__c.field-meta.xml
<CustomField>
    <fullName>UTM_Term__c</fullName>
    <label>UTM Term (Deprecated)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>UTM_Term</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/Marketing_Campaign__c.object-meta.xml
<CustomObject>
    <label>Marketing Campaign</label>
    <nameField>
        <label>Marketing Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Campaign__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cost_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/UTM_Campaign__c.field-meta.xml
<CustomField>
    <fullName>UTM_Campaign__c</fullName>
    <label>UTM Campaign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/UTM_Content__c.field-meta.xml
<CustomField>
    <fullName>UTM_Content__c</fullName>
    <label>UTM Content</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/UTM_Medium__c.field-meta.xml
<CustomField>
    <fullName>UTM_Medium__c</fullName>
    <label>UTM Medium</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/UTM_Source__c.field-meta.xml
<CustomField>
    <fullName>UTM_Source__c</fullName>
    <label>UTM Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Campaign__c/fields/UTM_Term__c.field-meta.xml
<CustomField>
    <fullName>UTM_Term__c</fullName>
    <label>UTM Term</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Cost_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Advertising</fullName>
    </customValue>
    <customValue>
        <fullName>Meetings</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Cost Category</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/UTM_Campaign.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Gratis dokument</fullName>
    </customValue>
    <customValue>
        <fullName>Gratis raadgivning</fullName>
    </customValue>
    <customValue>
        <fullName>Indhent tilbud</fullName>
    </customValue>
    <customValue>
        <fullName>Risikovurdering</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>Arvetest</fullName>
    </customValue>
    <customValue>
        <fullName>Kanvas</fullName>
    </customValue>
    <customValue>
        <fullName>Bestil dokument</fullName>
    </customValue>
    <customValue>
        <fullName>-</fullName>
    </customValue>
    <customValue>
        <fullName>Ukendt</fullName>
    </customValue>
    <customValue>
        <fullName>Cadence</fullName>
    </customValue>
    <customValue>
        <fullName>Mailkampagne - sommer 2023</fullName>
        <isActive>false</isActive>
        <label>Mailkampagne - sommer 2023</label>
    </customValue>
    <customValue>
        <fullName>Gratis foredrag</fullName>
        <isActive>false</isActive>
        <label>Gratis foredrag</label>
    </customValue>
    <customValue>
        <fullName>Gratis Rådgivning</fullName>
        <isActive>false</isActive>
        <label>Gratis Rådgivning</label>
    </customValue>
    <customValue>
        <fullName>konkurrence</fullName>
        <isActive>false</isActive>
        <label>konkurrence</label>
    </customValue>
    <masterLabel>UTM Campaign</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/UTM_Medium.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Andet</fullName>
    </customValue>
    <customValue>
        <fullName>Totalliv</fullName>
    </customValue>
    <customValue>
        <fullName>Calendly</fullName>
    </customValue>
    <customValue>
        <fullName>Findforsikring.dk</fullName>
    </customValue>
    <customValue>
        <fullName>Leadad</fullName>
    </customValue>
    <customValue>
        <fullName>Impressive Relations</fullName>
    </customValue>
    <customValue>
        <fullName>Tilmeldingsblanket</fullName>
    </customValue>
    <customValue>
        <fullName>Kundkontakter</fullName>
    </customValue>
    <customValue>
        <fullName>Seren</fullName>
    </customValue>
    <customValue>
        <fullName>PR Leads</fullName>
    </customValue>
    <customValue>
        <fullName>Gratis dokument</fullName>
    </customValue>
    <customValue>
        <fullName>Indhent tilbud</fullName>
    </customValue>
    <customValue>
        <fullName>Bobehandling</fullName>
    </customValue>
    <customValue>
        <fullName>Gratis raadgivning</fullName>
    </customValue>
    <customValue>
        <fullName>Söderberg &amp; Partners</fullName>
    </customValue>
    <customValue>
        <fullName>Dokument24</fullName>
    </customValue>
    <customValue>
        <fullName>Folkeskolen</fullName>
    </customValue>
    <customValue>
        <fullName>Andre influencers</fullName>
    </customValue>
    <customValue>
        <fullName>Adservice</fullName>
    </customValue>
    <customValue>
        <fullName>HK</fullName>
    </customValue>
    <customValue>
        <fullName>Bigsaver.dk</fullName>
    </customValue>
    <customValue>
        <fullName>BoligAdvokat24</fullName>
    </customValue>
    <customValue>
        <fullName>Dinfamiljejurist.nu</fullName>
    </customValue>
    <customValue>
        <fullName>Forsikringshj�lp</fullName>
    </customValue>
    <customValue>
        <fullName>Jyllandsposten</fullName>
    </customValue>
    <customValue>
        <fullName>Nyhedsbreve</fullName>
    </customValue>
    <customValue>
        <fullName>S�derberg &amp; Partners</fullName>
    </customValue>
    <customValue>
        <fullName>-</fullName>
    </customValue>
    <customValue>
        <fullName>Trafik</fullName>
    </customValue>
    <customValue>
        <fullName>Leadads</fullName>
    </customValue>
    <masterLabel>UTM Medium</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/UTM_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Foredrag</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Google-ads</fullName>
    </customValue>
    <customValue>
        <fullName>Ukendt</fullName>
    </customValue>
    <customValue>
        <fullName>Selvoprettet</fullName>
    </customValue>
    <customValue>
        <fullName>Affiliate</fullName>
    </customValue>
    <customValue>
        <fullName>MakeInfluence</fullName>
    </customValue>
    <customValue>
        <fullName>-</fullName>
    </customValue>
    <customValue>
        <fullName>dagensinfo</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Danish Website</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>BA</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
    </customValue>
    <customValue>
        <fullName>Imported</fullName>
    </customValue>
    <customValue>
        <fullName>Calendly</fullName>
    </customValue>
    <customValue>
        <fullName>CloudPage</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Acquaintance</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Meeting Booking</fullName>
    </customValue>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Visitkort</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Care</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Inbound Email</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Meeting Booker</fullName>
    </customValue>
    <customValue>
        <fullName>Referral Program</fullName>
    </customValue>
    <masterLabel>UTM Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/UTM_Term.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Andet</fullName>
    </customValue>
    <customValue>
        <fullName>30-49 - gift og samlevende</fullName>
    </customValue>
    <customValue>
        <fullName>3 procent lookalike af alle leads, gift og samlevende</fullName>
        <default>true</default>
        <label>3 procent lookalike af alle leads, gift og samlevende</label>
    </customValue>
    <customValue>
        <fullName>Alle mellem 50 til 64 aar - gift og samlevende</fullName>
    </customValue>
    <customValue>
        <fullName>Pre-booking</fullName>
    </customValue>
    <customValue>
        <fullName>Alle 25-65 år</fullName>
    </customValue>
    <customValue>
        <fullName>Popermo medlemmer</fullName>
    </customValue>
    <customValue>
        <fullName>Børnefamilier</fullName>
    </customValue>
    <customValue>
        <fullName>testamente</fullName>
    </customValue>
    <customValue>
        <fullName>testamentepris</fullName>
    </customValue>
    <customValue>
        <fullName>samlevertestamente</fullName>
    </customValue>
    <customValue>
        <fullName>Gratis raadgivning</fullName>
    </customValue>
    <customValue>
        <fullName>Gratis dokument</fullName>
    </customValue>
    <customValue>
        <fullName>din familie jurist</fullName>
    </customValue>
    <customValue>
        <fullName>Forældre med børn op til 8 år</fullName>
    </customValue>
    <customValue>
        <fullName>Kopimålgruppe 1-2 procent af alle leads</fullName>
    </customValue>
    <customValue>
        <fullName>alle-over-40</fullName>
    </customValue>
    <customValue>
        <fullName>online testamente</fullName>
    </customValue>
    <customValue>
        <fullName>45</fullName>
    </customValue>
    <customValue>
        <fullName>pris  testamente</fullName>
    </customValue>
    <customValue>
        <fullName>Alle over 30</fullName>
    </customValue>
    <customValue>
        <fullName>Remarketing åbnet men ikke tilmeldt</fullName>
    </customValue>
    <customValue>
        <fullName>1-3 procent lookalike</fullName>
    </customValue>
    <customValue>
        <fullName>28-40-aar</fullName>
    </customValue>
    <customValue>
        <fullName>testamente  opret</fullName>
    </customValue>
    <customValue>
        <fullName>pris testamente</fullName>
    </customValue>
    <customValue>
        <fullName>testamente pris</fullName>
    </customValue>
    <customValue>
        <fullName>3 procent m%C3%A5lgruppe af alle emner</fullName>
    </customValue>
    <customValue>
        <fullName>samlever  testamente</fullName>
    </customValue>
    <customValue>
        <fullName>testamente  online</fullName>
    </customValue>
    <masterLabel>UTM Term</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CS_Utility.cls
/*
   * @ Version : 1.0
   * @ Created Date : 2021-12-17
   * @Description : CS is for Cost System this class will be used as utility for campaign spend process script.
*/
public with sharing class CS_Utility {
    /*
    * @Description  method to fetch the marketing campaign record.
    * @Params       marketingCampaignInstance
    * @Return       String 
    */
    public static List<Marketing_Campaign__c> FetchMarketingCampaign(List<String> marketingCampaignId){
        try {
            if (marketingCampaignId.isEmpty()) {
                return null;
            }
            List<Marketing_Campaign__c> marketingCampaignList = new List<Marketing_Campaign__c>();
            marketingCampaignList = [Select UTM_Campaign__c,UTM_Content__c,UTM_Medium__c,UTM_Source__c,UTM_Term__c,Cost_Category__c FROM Marketing_Campaign__c WHERE Id IN: marketingCampaignId];
            if (!marketingCampaignList.isEmpty()) {
                return marketingCampaignList;
            }
        } catch(Exception ex){
            DFJ_ErrorController.addErrorLogs('', 'Getting all Marketing Campaigns records.', ex.getMessage(), 'Error', 'CS_Utility.FetchMarketingCampaign', String.valueOf(ex.getLineNumber()));
        }
        return null;
    }

    /*
    * @Description  method to fetch records by the query.
    * @Params       marketingCampaign,spendPeriod
    * @Return       List<SObject>
    */
    public static List<SObject> FetchRecordsByQuery(String query,Set<String> leadIds,String marketingCampaignId,String processPeriod){
        try {
            if (String.isBlank(query)) {
                return null;
            }
            
            List<SObject> sObjFetched = Database.query(query);
            if (sObjFetched != null && !sObjFetched.isEmpty() ) {
                return sObjFetched;
            }
        } catch (Exception ex) {
            DFJ_ErrorController.addErrorLogs('', 'Fetching records using query', ex.getMessage(), 'Error', 'CS_Utility.FetchRecordsByQuery', String.valueOf(ex.getLineNumber()));
            
        }
        return null;
    }

    /*
    * @Description  Wrapper to store the processperiod from and to field.
    */
    public class ProcessPeriod{
        public Datetime fromDate;
        public Datetime toDate;
    }

    /*
    * @Description  method to build spend period query.
    * @Params       whereClause,limitOfRecords
    * @Return       String 
    */
    public static String QueryToFetchSpendPeriod(String whereClause,String limitOfRecords){
        try {
            List<String> fieldsList = new List<String>{'Id','Name','Marketing_Campaign__c','Period_end_time__c','Period_start_time__c','Total_spend__c'};
            if (Test.isRunningTest() && whereClause=='asdf') {
                Decimal CodeCoverage = 10/0;
            }
            return CS_Selector.FetchMarketingSpendPeriod(fieldsList, whereClause, limitOfRecords);
        } catch (Exception ex) {
            DFJ_ErrorController.addErrorLogs('', 'Fetching all spend period from marketing campaign.', ex.getMessage(), 'Error', 'CS_Utility.QueryToFetchSpendPeriod', String.valueOf(ex.getLineNumber()));
        }
        return null;
    }

    /*
    * @Description  method to build lead query.
    * @Params       whereClause,limitOfRecords
    * @Return       String 
    */
    public static String QueryToFetchLeads(String whereClause,String limitOfRecords){
        try {
            List<String> fieldsList = new List<String>{'Id','Name','IsConverted','CreatedDate','Marketing_Campaign__c'};
            if (Test.isRunningTest() && whereClause=='asdf') {
                Decimal CodeCoverage = 10/0;
            }
            return CS_Selector.FetchLeadsQuery(fieldsList, whereClause, limitOfRecords);
        } catch (Exception ex) {
            DFJ_ErrorController.addErrorLogs('', 'Building query to get leads.', ex.getMessage(), 'Error', 'CS_Utility.QueryToFetchLeads', String.valueOf(ex.getLineNumber()));
        }
        return null;
    }

    /*
    * @Description  method to build query to fetch converted leads account.
    * @Params       whereClause,limitOfRecords
    * @Return       String 
    */
    public static String QueryToFetchAccount(String whereClause,String limitOfRecords){
        try {
            List<String> fieldsList = new List<String>{'Id','Name','Lead__c'};
            if (Test.isRunningTest() && whereClause=='asdf') {
                Decimal CodeCoverage = 10/0;
            }
            return CS_Selector.FetchAccountQuery(fieldsList, whereClause, limitOfRecords);
        } catch (Exception ex) {
            DFJ_ErrorController.addErrorLogs('', 'Building query to get accounts.', ex.getMessage(), 'Error', 'CS_Utility.QueryToFetchAccount', String.valueOf(ex.getLineNumber()));
            
        }
        return null;
    }

}