force-app/main/default/objects/Email_Message__b/Email_Message__b.object-meta.xml
<CustomObject>
    <label>Email Message</label>
    <pluralLabel>Email Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Email_Message__b/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <label>Activity Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/CcAddress__c.field-meta.xml
<CustomField>
    <fullName>CcAddress__c</fullName>
    <label>CC Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/ClientThreadIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ClientThreadIdentifier__c</fullName>
    <label>ClientThreadIdentifier</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/EmailRoutingAddressId__c.field-meta.xml
<CustomField>
    <fullName>EmailRoutingAddressId__c</fullName>
    <label>EmailRoutingAddressId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/EmailTemplateId__c.field-meta.xml
<CustomField>
    <fullName>EmailTemplateId__c</fullName>
    <label>EmailTemplateId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/FirstOpenedDate__c.field-meta.xml
<CustomField>
    <fullName>FirstOpenedDate__c</fullName>
    <label>First Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/FromAddress__c.field-meta.xml
<CustomField>
    <fullName>FromAddress__c</fullName>
    <label>From Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/FromId__c.field-meta.xml
<CustomField>
    <fullName>FromId__c</fullName>
    <label>From Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/FromName__c.field-meta.xml
<CustomField>
    <fullName>FromName__c</fullName>
    <label>From Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/HTMLBody__c.field-meta.xml
<CustomField>
    <fullName>HTMLBody__c</fullName>
    <label>HTML Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <label>SF Record ID</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/Incoming__c.field-meta.xml
<CustomField>
    <fullName>Incoming__c</fullName>
    <label>Is Incoming</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/IsBounced__c.field-meta.xml
<CustomField>
    <fullName>IsBounced__c</fullName>
    <label>Is Bounced</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/IsOpened__c.field-meta.xml
<CustomField>
    <fullName>IsOpened__c</fullName>
    <label>Is Opened</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/IsTracked__c.field-meta.xml
<CustomField>
    <fullName>IsTracked__c</fullName>
    <label>Is Tracked</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/LastOpenedDate__c.field-meta.xml
<CustomField>
    <fullName>LastOpenedDate__c</fullName>
    <label>Last Opened</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/MessageDate__c.field-meta.xml
<CustomField>
    <fullName>MessageDate__c</fullName>
    <label>Message Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/MessageIdentifier__c.field-meta.xml
<CustomField>
    <fullName>MessageIdentifier__c</fullName>
    <label>MessageIdentifier</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/RelatedToId__c.field-meta.xml
<CustomField>
    <fullName>RelatedToId__c</fullName>
    <label>Related To</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/ReplyToEmailMessageId__c.field-meta.xml
<CustomField>
    <fullName>ReplyToEmailMessageId__c</fullName>
    <label>ReplyToEmailMessageId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/TextBody__c.field-meta.xml
<CustomField>
    <fullName>TextBody__c</fullName>
    <label>Text Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/ThreadIdentifier__c.field-meta.xml
<CustomField>
    <fullName>ThreadIdentifier__c</fullName>
    <label>ThreadIdentifier</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/ToAddress__c.field-meta.xml
<CustomField>
    <fullName>ToAddress__c</fullName>
    <label>To Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Email_Message__b/fields/ValidatedFromAddress__c.field-meta.xml
<CustomField>
    <fullName>ValidatedFromAddress__c</fullName>
    <label>ValidatedFromAddress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DFJ_EmailMessageBatchClass.cls
public class DFJ_EmailMessageBatchClass implements Database.Batchable<SObject>, Database.Stateful, DFJ_EmailMessageArchiver {
    
    private Set<Id> successfulInsertIds = new Set<Id>();
    private String dateFilter;
    private DFJ_EmailMessageArchiver archiver;   
    private Set<Id> failedIds = new Set<Id>();
   
    public DFJ_EmailMessageBatchClass(String filter) {
        this.archiver = this;  
        this.dateFilter = filter;
    } 
    
    public DFJ_EmailMessageBatchClass(DFJ_EmailMessageArchiver archiver, String filter) {
        this.archiver = archiver;
        this.dateFilter = filter;
    } 
 
    public Database.SaveResult[] insertRecords(List<Email_Message__b> records) {
        if (!records.isEmpty() && !Test.isRunningTest()) {
            return Database.insertImmediate(records);
        }
        return new List<Database.SaveResult>();
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id,Name,ActivityId,CcAddress,ClientThreadIdentifier,CreatedDate,EmailRoutingAddressId ' +
            ',EmailTemplateId,FirstOpenedDate,FromAddress,FromId,FromName,Headers,HtmlBody,Incoming,IsBounced,IsOpened,IsTracked,' +
            'LastOpenedDate,MessageDate,MessageIdentifier,RelatedToId,ReplyToEmailMessageId,Source,Status,Subject,TextBody,' +
            'ThreadIdentifier ,ToAddress,ValidatedFromAddress ' +
            'FROM EmailMessage WHERE ' + dateFilter
        );
    }
    
   public void execute(Database.BatchableContext bc, List<SObject> scope) {
   if (scope != null && !scope.isEmpty()) {    
        List<Email_Message__b> emailMessageToInsert = new List<Email_Message__b>();
        for (SObject sObj : scope) {
            EmailMessage emailMessage = (EmailMessage) sObj; 
            Email_Message__b emailMessageRecord = new Email_Message__b();
            emailMessageRecord.ActivityId__c = (emailMessage.ActivityId!= null) ? String.valueOf(emailMessage.ActivityId) : null;
            emailMessageRecord.CcAddress__c = emailMessage.CcAddress != null ? emailMessage.CcAddress : ' ';
            emailMessageRecord.ClientThreadIdentifier__c = emailMessage.ClientThreadIdentifier != null ? emailMessage.ClientThreadIdentifier : ' ';
            emailMessageRecord.CreatedDate__c = emailMessage.CreatedDate;
            emailMessageRecord.FirstOpenedDate__c = emailMessage.FirstOpenedDate != null ? emailMessage.FirstOpenedDate : null;
            emailMessageRecord.FromAddress__c = emailMessage.FromAddress != null ? emailMessage.FromAddress : ' ';
            emailMessageRecord.FromId__c = (emailMessage.FromId != null) ? String.valueOf(emailMessage.FromId) : null;
            emailMessageRecord.FromName__c = emailMessage.FromName != null ? emailMessage.FromName : ' ';
            emailMessageRecord.Headers__c = emailMessage.Headers != null ? emailMessage.Headers : ' ';
            emailMessageRecord.HtmlBody__c = emailMessage.HtmlBody != null ? emailMessage.HtmlBody : ' ';   
            emailMessageRecord.IsBounced__c = (emailMessage.IsBounced == true) ? 'True' : 'False';
            emailMessageRecord.Incoming__c = (emailMessage.Incoming == true) ? 'True' : 'False';
            emailMessageRecord.IsOpened__c = (emailMessage.IsOpened == true) ? 'True' : 'False';
            emailMessageRecord.IsTracked__c = (emailMessage.IsTracked == true) ? 'True' : 'False';              
            emailMessageRecord.LastOpenedDate__c = emailMessage.LastOpenedDate != null ? emailMessage.LastOpenedDate : null;
            emailMessageRecord.MessageDate__c = emailMessage.MessageDate != null ? emailMessage.MessageDate : null;
            emailMessageRecord.MessageIdentifier__c = emailMessage.MessageIdentifier != null ? emailMessage.MessageIdentifier : ' ';
            emailMessageRecord.Name__c = emailMessage.Name != null ? emailMessage.Name : ' ';
            emailMessageRecord.RelatedToId__c = (emailMessage.RelatedToId != null) ? String.valueOf(emailMessage.RelatedToId) : null;
            emailMessageRecord.ID__c = emailMessage.Id;
            emailMessageRecord.Source__c = emailMessage.Source != null ? emailMessage.Source : ' ';
            emailMessageRecord.Status__c = emailMessage.Status != null ? emailMessage.Status : ' ';
            emailMessageRecord.Subject__c = emailMessage.Subject != null ? emailMessage.Subject : ' ';
            emailMessageRecord.TextBody__c = emailMessage.TextBody != null ? emailMessage.TextBody : ' ';
            emailMessageRecord.ThreadIdentifier__c = emailMessage.ThreadIdentifier != null ? emailMessage.ThreadIdentifier : ' ';
            emailMessageRecord.ToAddress__c = emailMessage.ToAddress != null ? emailMessage.ToAddress : ' ';
            emailMessageRecord.ValidatedFromAddress__c = emailMessage.ValidatedFromAddress != null ? emailMessage.ValidatedFromAddress : ' ';
            emailMessageRecord.EmailRoutingAddressId__c = (emailMessage.EmailRoutingAddressId != null) ? String.valueOf(emailMessage.EmailRoutingAddressId) : null;
            emailMessageRecord.EmailTemplateId__c= (emailMessage.EmailTemplateId != null) ? String.valueOf(emailMessage.EmailTemplateId) : null;
            emailMessageRecord.ReplyToEmailMessageId__c = (emailMessage.ReplyToEmailMessageId != null) ? String.valueOf(emailMessage.ReplyToEmailMessageId) : null;
            emailMessageToInsert.add(emailMessageRecord);
        }
        if (!emailMessageToInsert.isEmpty()) {
            try {
                Database.SaveResult[] results = archiver.insertRecords(emailMessageToInsert); 
               for (Integer i = 0; i < results.size(); i++) {
                    Database.SaveResult sr = results[i]; 
                    String recordIdentifier = emailMessageToInsert[i].ID__c; 
                    if (!sr.isSuccess()) {
                        failedIds.add(recordIdentifier);
                    } else {
                        successfulInsertIds.add(recordIdentifier);   
                    }
                }   
            } catch (Exception e) {
               System.debug('error:-->'+ e.getMessage()+ 'on line No-->'+ e.getLineNumber());
            }
        }
    } 
}
 
    public void finish(Database.BatchableContext bc) {
        System.debug('failedIds: ' + failedIds);
        if (!successfulInsertIds.isEmpty()) {
            Database.executeBatch(new DFJ_DeleteRecords(successfulInsertIds, 'EmailMessage'), 2000);
        } 
    }
    
    public class BatchParams {
        @InvocableVariable(required=false) public Date startDate;
        @InvocableVariable(required=true) public Date endDate;
    }
    
    @InvocableMethod(label='Run Email Message Batch')
    public static void runBatch(List<BatchParams> paramsList) {
        BatchParams params = (paramsList != null && !paramsList.isEmpty()) ? paramsList[0] : new BatchParams();
        String filter; 
        Date endDate = params.endDate;
        Date startDate = params.startDate;
        DateTime endDT = DateTime.newInstance(endDate, Time.newInstance(23, 59, 59, 0));
        if (startDate != null) {
            DateTime startDT = DateTime.newInstance(startDate, Time.newInstance(0, 0, 0, 0));
            filter = 'CreatedDate >= ' + startDT.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'') + ' AND CreatedDate <= ' + endDT.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        } else {
            filter = 'CreatedDate <= ' + endDT.format('yyyy-MM-dd\'T\'HH:mm:ss\'Z\'');
        }        
        Database.executeBatch(new DFJ_EmailMessageBatchClass(filter), 2000);
    }
}