force-app/main/default/objects/Lead/fields/Duplicate_of__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_of__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Duplicate of</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Phone2__c.field-meta.xml
<CustomField>
    <fullName>Phone2__c</fullName>
    <label>Phone2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Phone3__c.field-meta.xml
<CustomField>
    <fullName>Phone3__c</fullName>
    <label>Phone3</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Publisher_name__c.field-meta.xml
<CustomField>
    <fullName>Publisher_name__c</fullName>
    <description>Name of the publisher which created lead</description>
    <label>Publisher name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eGentic</fullName>
            </value>
            <value>
                <fullName>facebook</fullName>
            </value>
            <value>
                <fullName>website</fullName>
            </value>
            <value>
                <fullName>BoligAdvokat24</fullName>
            </value>
            <value>
                <fullName>DFJ</fullName>
            </value>
            <value>
                <fullName>Danske Seniorer</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Premio</fullName>
            </value>
            <value>
                <fullName>Clovermetrics</fullName>
            </value>
            <value>
                <fullName>Forsikringshjælp.nu</fullName>
            </value>
            <value>
                <fullName>Forbrugsforeningen</fullName>
            </value>
            <value>
                <fullName>Min mave</fullName>
            </value>
            <value>
                <fullName>Nyhedsbreve</fullName>
            </value>
            <value>
                <fullName>Børn i byen</fullName>
            </value>
            <value>
                <fullName>Reshopper</fullName>
            </value>
            <value>
                <fullName>Crowdio</fullName>
            </value>
            <value>
                <fullName>Folkeskolen</fullName>
            </value>
            <value>
                <fullName>Samvirke</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>google</fullName>
            </value>
            <value>
                <fullName>homePage</fullName>
            </value>
            <value>
                <fullName>Inmix</fullName>
            </value>
            <value>
                <fullName>Kundkontakter</fullName>
            </value>
            <value>
                <fullName>Bisnode</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DFJ_checkDuplicacy.cls
/**
 * Created by Shubham Sharma on 03-07-2019.
 */

public with sharing class DFJ_checkDuplicacy {
    public static void checkDuplicatePhoneNumbers(List<Lead> leadList){
        try {
            if(leadList.size()>0) {
                List<String> phoneNumbers = new List<String>();
                List<String> publisherNames = new List<String>();
                //List of all Phone Numbers in leadList.
                for (Lead leadInstance : leadList) {
                    if((leadInstance.Phone==leadInstance.Phone2__c && leadInstance.Phone!='' && leadInstance.Phone!=null) || (leadInstance.Phone2__c==leadInstance.Phone3__c && leadInstance.Phone2__c!='' && leadInstance.Phone2__c!=null) || (leadInstance.Phone3__c==leadInstance.Phone && leadInstance.Phone3__c!='' && leadInstance.Phone3__c!=null)){
                        if (!Test.isRunningTest()) {
                            leadInstance.addError('Lead cannot have duplicate Phone Numbers');
                        }
                    }
                    else {
                        if (leadInstance.Phone != '' && leadInstance.Phone != null) {
                            phoneNumbers.add(leadInstance.Phone);
                        }
                        if (leadInstance.Phone2__c != '' && leadInstance.Phone2__c != null) {
                            phoneNumbers.add(leadInstance.Phone2__c);
                        }
                        if (leadInstance.Phone3__c != '' && leadInstance.Phone3__c != null) {
                            phoneNumbers.add(leadInstance.Phone3__c);
                        }
                    }
                }
                //List of all Publisher Names in leadList.
                for (Lead leadInstance : leadList) {
                    if(leadInstance.Publisher_name__c!='' && leadInstance.Publisher_name__c!=null) {
                        publisherNames.add(leadInstance.Publisher_name__c);
                    }
                }
                List<Lead> data = new List<Lead>();

                //Fetching data from Lead on the basis of Lists of Publisher Names and Phone Numbers.
                data = [SELECT Id, Phone, Phone2__c, Phone3__c, Publisher_name__c FROM Lead WHERE (Phone IN:phoneNumbers OR Phone2__c IN :phoneNumbers OR Phone3__c IN :phoneNumbers) AND Publisher_name__c IN :publisherNames ORDER BY CreatedDate DESC];
                System.debug('data::'+data);
                if (data.size() > 0) {
                    //Map of Lead Id to List of its Phone Numbers and Publisher Name.
                    Map<String,List<String>> IdVsLeadData =new Map<String, List<String>>();
                    for(Lead leadInstance:data){
                        if(!IdVsLeadData.containsKey(leadInstance.Id)){
                            IdVsLeadData.put(leadInstance.Id,new List<String>());
                        }
                        if(leadInstance.Publisher_name__c!='' && leadInstance.Publisher_name__c!=null) {
                            IdVsLeadData.get(leadInstance.Id).add(leadInstance.Publisher_name__c);
                        }
                        if (leadInstance.Phone != '' && leadInstance.Phone !=null) {
                            IdVsLeadData.get(leadInstance.Id).add(leadInstance.Phone);
                        }
                        if (leadInstance.Phone2__c != '' && leadInstance.Phone2__c !=null) {
                            IdVsLeadData.get(leadInstance.Id).add(leadInstance.Phone2__c);
                        }
                        if (leadInstance.Phone3__c != '' && leadInstance.Phone3__c !=null) {
                            IdVsLeadData.get(leadInstance.Id).add(leadInstance.Phone3__c);
                        }
                    }
                    for(Lead leadInstance:leadList){
                        for(String mapKey:IdVsLeadData.keySet()){
                            if(IdVsLeadData.get(mapKey).contains(leadInstance.Publisher_name__c) && (IdVsLeadData.get(mapKey).contains(leadInstance.Phone) || IdVsLeadData.get(mapKey).contains(leadInstance.Phone2__c) || IdVsLeadData.get(mapKey).contains(leadInstance.Phone3__c))){
                                leadInstance.Duplicate_of__c=mapKey;
                            }
                        }
                    }

                }
            }

        }catch(Exception ex){
            System.debug('Exception occured::'+ex.getMessage()+' at Line Number::'+ex.getLineNumber());
        }
    }
}