force-app/main/default/objects/Lead/fields/Har_accepteret_medlemsbetingelser__c.field-meta.xml
<CustomField>
    <fullName>Har_accepteret_medlemsbetingelser__c</fullName>
    <label>Har accepteret medlemsbetingelser</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Item #1</fullName>
            </value>
            <value>
                <fullName>true</fullName>
            </value>
            <value>
                <fullName>JA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Member email.</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Is_customer__c.field-meta.xml
<CustomField>
    <fullName>Is_customer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is customer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Member phone.</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Membership__c/fields/Sign_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Sign_up_Date__c</fullName>
    <label>Sign-up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DFJ_LeadForMembership_Helper.cls
/*
   * @ Version : 1.0
   * @ Created Date : 2021-12-14
   * @Description : Helper class to create membership record after lead creation.
*/
public with sharing class DFJ_LeadForMembership_Helper {
    /*
    * @Description  method to create the membership record on creation of Lead record.
    * @Return       Boolean
    */
    public static Boolean CreateMembership_Apex(List<Lead> leadList){
        try {
            
            List<Membership__c> memberListInstance = new List<Membership__c>();
            if (!leadList.isEmpty()) {            
                for (Lead leadLoop : leadList) {
                    if (leadLoop.Har_accepteret_medlemsbetingelser__c != null && (leadLoop.Har_accepteret_medlemsbetingelser__c.equals('true') || leadLoop.Har_accepteret_medlemsbetingelser__c.equals('JA') || leadLoop.Har_accepteret_medlemsbetingelser__c.contains('1'))) {
                        memberListInstance.add(new membership__c(Lead__c=leadLoop.Id,Name=(String.isBlank(leadLoop.FirstName) ? leadLoop.LastName : leadLoop.FirstName+' '+leadLoop.LastName),First_Name__c=leadLoop.FirstName,Last_Name__c=leadLoop.Lastname,Email__c=leadLoop.Email,Is_customer__c=false,Phone__c=leadLoop.Phone,Sign_up_Date__c=System.Today()));
                    }
                    
                }
            }
            if (!memberListInstance.isEmpty()) {
                insert memberListInstance;
                return true;
            }
            
        } catch (Exception ex) {
            DFJ_ErrorController.addErrorLogs('', 'Inserting membership on lead creation.', ex.getMessage(), 'Error', 'DFJ_LeadForMembership_Helper.CreateMembership_Apex', String.valueOf(ex.getLineNumber()));
        }
        return false;
    }
}