force-app/main/default/objects/Lead/fields/Lead_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Group_Name__c</fullName>
    <label>Lead Group Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kampagne 2</fullName>
            </value>
            <value>
                <fullName>Kampagne 3</fullName>
            </value>
            <value>
                <fullName>DFJ B2B</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Kampagne 1</fullName>
                <default>true</default>
                <label>Kampagne 1</label>
            </value>
            <value>
                <fullName>TD Kampagne 1</fullName>
            </value>
            <value>
                <fullName>Genåbnet</fullName>
            </value>
            <value>
                <fullName>Dublet Kampagne</fullName>
            </value>
            <value>
                <fullName>Norrina</fullName>
            </value>
            <value>
                <fullName>Nina</fullName>
            </value>
            <value>
                <fullName>Denis</fullName>
            </value>
            <value>
                <fullName>Flemming</fullName>
            </value>
            <value>
                <fullName>Testamente Sverige</fullName>
            </value>
            <value>
                <fullName>Lotte Gravers</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>Andet</fullName>
            </value>
            <value>
                <fullName>Parkeret</fullName>
            </value>
            <value>
                <fullName>Dublet Kampagne DK</fullName>
            </value>
            <value>
                <fullName>Dublet Kampagne SE</fullName>
            </value>
            <value>
                <fullName>Mailkampagne</fullName>
            </value>
            <value>
                <fullName>Facebook Burton</fullName>
            </value>
            <value>
                <fullName>Kampagne DK</fullName>
            </value>
            <value>
                <fullName>Kampagne SE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/telegenta__Has_Appointment__c.field-meta.xml
<CustomField>
    <fullName>telegenta__Has_Appointment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates Lead has a recall appointment and NextCallTime contains the appointment time</description>
    <inlineHelpText>Indicates Lead has a recall appointment and NextCallTime contains the appointment time</inlineHelpText>
    <label>Has Appointment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/telegenta__Invalid_Reason__c.field-meta.xml
<CustomField>
    <fullName>telegenta__Invalid_Reason__c</fullName>
    <description>Reason for lead being invalid</description>
    <inlineHelpText>Reason for lead being invalid</inlineHelpText>
    <label>Invalid Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partnerdublet</fullName>
            </value>
            <value>
                <fullName>Forkert person</fullName>
            </value>
            <value>
                <fullName>Under 18</fullName>
            </value>
            <value>
                <fullName>Eksisterende kunde</fullName>
            </value>
            <value>
                <fullName>Blacklist</fullName>
            </value>
            <value>
                <fullName>Forstår ikke dansk</fullName>
            </value>
            <value>
                <fullName>Ikke kreditgodkendt</fullName>
            </value>
            <value>
                <fullName>Number incorrect</fullName>
                <label>Nummer eksisterer ikke</label>
            </value>
            <value>
                <fullName>TestLead</fullName>
            </value>
            <value>
                <fullName>Dublet</fullName>
            </value>
            <value>
                <fullName>Nummer blokeret</fullName>
            </value>
            <value>
                <fullName>MAXCALL</fullName>
            </value>
            <value>
                <fullName>Oprydning</fullName>
            </value>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>Unverified Prospect</fullName>
            </value>
            <value>
                <fullName>Not enough seats available</fullName>
            </value>
            <value>
                <fullName>Not accessible (e.g. no parking, bad location)</fullName>
            </value>
            <value>
                <fullName>Poor acoustics or layout for presentations</fullName>
            </value>
            <value>
                <fullName>Kitchen closed during our event hours</fullName>
            </value>
            <value>
                <fullName>Doesn’t allow external guests</fullName>
            </value>
            <value>
                <fullName>Lacks necessary licenses (e.g. alcohol)</fullName>
            </value>
            <value>
                <fullName>Under renovation or temporarily closed</fullName>
            </value>
            <value>
                <fullName>Fjernet</fullName>
                <isActive>false</isActive>
                <label>Fjernet</label>
            </value>
            <value>
                <fullName>Lukket af admin</fullName>
                <isActive>false</isActive>
                <label>Lukket af admin</label>
            </value>
            <value>
                <fullName>Unavailable</fullName>
                <isActive>false</isActive>
                <label>Unavailable</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/telegenta__Last_Contact_State__c.field-meta.xml
<CustomField>
    <fullName>telegenta__Last_Contact_State__c</fullName>
    <description>Last outcome of call attempt</description>
    <inlineHelpText>Last outcome of call attempt</inlineHelpText>
    <label>Last Contact State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No answer or voicemail</fullName>
            </value>
            <value>
                <fullName>Number busy</fullName>
            </value>
            <value>
                <fullName>Don&apos;t have time right now</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Got appointment</fullName>
                <label>Appointment</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Missed Appointment</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/telegenta__Next_Call_Time__c.field-meta.xml
<CustomField>
    <fullName>telegenta__Next_Call_Time__c</fullName>
    <description>Minimum time before lead can be called again</description>
    <inlineHelpText>Minimum time before lead can be called again</inlineHelpText>
    <label>Next Call Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/telegenta__Not_Interested_Reason__c.field-meta.xml
<CustomField>
    <fullName>telegenta__Not_Interested_Reason__c</fullName>
    <description>Reason for lead not being interested</description>
    <inlineHelpText>Reason for lead not being interested</inlineHelpText>
    <label>Not Interested Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Afvist i introen</fullName>
            </value>
            <value>
                <fullName>Kunden lagde på</fullName>
            </value>
            <value>
                <fullName>Har ALLE dokumenter</fullName>
            </value>
            <value>
                <fullName>Vil selv vende tilbage</fullName>
            </value>
            <value>
                <fullName>Aldrig tilmeldt sig</fullName>
            </value>
            <value>
                <fullName>Standpunkt uændret</fullName>
            </value>
            <value>
                <fullName>Ønsker ikke at deltage i et foredrag</fullName>
            </value>
            <value>
                <fullName>For dyrt</fullName>
            </value>
            <value>
                <fullName>Har ikke råd</fullName>
            </value>
            <value>
                <fullName>Er allerede i gang</fullName>
            </value>
            <value>
                <fullName>Opfølgning 3-6 måneder</fullName>
            </value>
            <value>
                <fullName>Besvarer ikke længere</fullName>
            </value>
            <value>
                <fullName>Modtager kun mail</fullName>
            </value>
            <value>
                <fullName>Misforstået kampagnebudskab</fullName>
            </value>
            <value>
                <fullName>Ønsker ikke kontakt - Foredrag</fullName>
            </value>
            <value>
                <fullName>Ønsker at deltage i foredrag først</fullName>
            </value>
            <value>
                <fullName>Annullerede møde</fullName>
            </value>
            <value>
                <fullName>Call After Hours</fullName>
            </value>
            <value>
                <fullName>Not enough compensation per guest</fullName>
            </value>
            <value>
                <fullName>Not enough compensation for venue rental</fullName>
            </value>
            <value>
                <fullName>Not willing to host lectures at all</fullName>
            </value>
            <value>
                <fullName>Doesn&apos;t want external events at the venue</fullName>
            </value>
            <value>
                <fullName>Management rejected the concept</fullName>
            </value>
            <value>
                <fullName>Bad prior experience with similar events</fullName>
            </value>
            <value>
                <fullName>Not interested in weekday bookings</fullName>
            </value>
            <value>
                <fullName>Only interested in private/corporate bookings</fullName>
            </value>
            <value>
                <fullName>Already has too many events</fullName>
            </value>
            <value>
                <fullName>Prefers to focus on internal customers</fullName>
            </value>
            <value>
                <fullName>Not open to collaboration with third parties</fullName>
            </value>
            <value>
                <fullName>-</fullName>
                <isActive>false</isActive>
                <label>-</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/telegenta__Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>telegenta__Phone_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Phone Number</label>
    <referenceTo>telegenta__Phone_Number__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/telegenta__Total_calls__c.field-meta.xml
<CustomField>
    <fullName>telegenta__Total_calls__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/telegenta__Unsuccessful_Calls__c.field-meta.xml
<CustomField>
    <fullName>telegenta__Unsuccessful_Calls__c</fullName>
    <label>Unsuccessful Calls</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SDCallCampaignStateCreation.cls
public class SDCallCampaignStateCreation {
    public static List<telegenta__Call_Campaign_State__c> UpsertCallCampaignStateForRecord_Apex(){
        try{
            String commonFilterQuery = '';
            DateTime currentTime = DateTime.now();
            List<Lead> leadList = new List<Lead>();
            List<Lead> leadWithOutCCSList = new List<Lead>();
            List<telegenta__Call_Campaign_State__c> callCampaignStateList = new List<telegenta__Call_Campaign_State__c>();
            List<telegenta__Call_Campaign_State__c> callCampaignStateToUpsertList = new List<telegenta__Call_Campaign_State__c>();
            List<telegenta__Call_Campaign_State__c> callCampaignStateInstanceToUpsertList = new List<telegenta__Call_Campaign_State__c>();
            Map<Id,Lead> LeadIdVsLead = new Map<Id,Lead>();
            Set<String> LeadIdSet = new Set<String>();
            Map<String,List<Lead>> LeadGroupNameVsLeads = new Map<String,List<Lead>>();
            Map<String,String> LeadGroupNameVsCallCampaignId = new Map<String,String>();
            Map<Id,List<telegenta__Call_Campaign_State__c>> LeadIdVsCallCampaignStates = new Map<Id,List<telegenta__Call_Campaign_State__c>>();
            List<telegenta__Lead_group__c> leadGroupsList = new List<telegenta__Lead_group__c>();
            String outcomeId = '';
            commonFilterQuery = 'telegenta__Last_Contact_State__c = \''+'Got Appointment'+'\' AND telegenta__Next_Call_Time__c != null AND telegenta__Next_Call_Time__c > :currentTime';
            String query = 'SELECT Status,Name,Lead_Group_name__c,telegenta__Total_calls__c,telegenta__Phone_number_Id__c,telegenta__Phone_Number__c,telegenta__Next_Call_Time__c,telegenta__Last_Contact_State__c,telegenta__Unsuccessful_Calls__c,telegenta__Not_Interested_Reason__c,telegenta__Invalid_Reason__c FROM Lead WHERE '+commonFilterQuery+' LIMIT 50000';
            
            leadList = Database.query(query);
            List<telegenta__Outcome__c> outcomeList = new List<telegenta__Outcome__c>();
            outcomeList = [SELECT Id,Name FROM telegenta__Outcome__c WHERE Name = 'Appointment' LIMIT 1];
            if(!outcomeList.isEmpty()){
                outcomeId = outcomeList[0].Id;
            }
            if(!leadList.isEmpty()){
                                System.debug('leadList ====>>'+JSON.serialize(leadList));
                System.debug('leadList size====>>'+leadList.size());
                for(Lead leadLoop : leadList){
                    LeadIdVsLead.put(leadLoop.Id,leadLoop);
                }  
                callCampaignStateList = [SELECT Id, telegenta__Next_Call_Time__c,telegenta__Unsuccessful_calls__c,telegenta__Total_Unsucccessful_Call__c, telegenta__Total_Calls__c,telegenta__Last_Call_Time__c,telegenta__Lead__c, telegenta__Last_Outcome__c,telegenta__Has_appointment__c,telegenta__Call_Campaign__c FROM telegenta__Call_Campaign_State__c WHERE telegenta__Lead__c IN : LeadIdVsLead.keySet() LIMIT 10000];
                if(!callCampaignStateList.isEmpty()){
                    for(telegenta__Call_Campaign_State__c callCampaignStateLoop : callCampaignStateList){
                        if(!LeadIdVsCallCampaignStates.containsKey(callCampaignStateLoop.telegenta__Lead__c)){
                            LeadIdVsCallCampaignStates.put(callCampaignStateLoop.telegenta__Lead__c,new List<telegenta__Call_Campaign_State__c>());
                        }
                        if(callCampaignStateLoop.telegenta__Next_Call_Time__c != null){
                            if(LeadIdVsLead.get(callCampaignStateLoop.telegenta__Lead__c).telegenta__Next_Call_Time__c != callCampaignStateLoop.telegenta__Next_Call_Time__c){
                                LeadIdVsCallCampaignStates.get(callCampaignStateLoop.telegenta__Lead__c).add(callCampaignStateLoop);
                            }
                        } else{
                            LeadIdVsCallCampaignStates.get(callCampaignStateLoop.telegenta__Lead__c).add(callCampaignStateLoop);  
                        }            
                    }
                    leadWithOutCCSList = [SELECT Status, Name,Lead_Group_name__c,telegenta__Total_calls__c,telegenta__Phone_number_Id__c,telegenta__Phone_Number__c, telegenta__Next_Call_Time__c, telegenta__Not_Interested_Reason__c, telegenta__Invalid_Reason__c  FROM Lead WHERE Id NOT IN :LeadIdVsCallCampaignStates.keySet() AND Id IN : LeadIdVsLead.keySet() LIMIT 10000];            
                }
                System.debug('LeadIdVsCallCampaignStates ====>>'+JSON.serialize(LeadIdVsCallCampaignStates));
                System.debug('leadWithOutCCSList ====>>'+JSON.serialize(leadWithOutCCSList));
                System.debug('leadWithOutCCSList size====>>'+leadWithOutCCSList.size());
                if(!leadWithOutCCSList.isEmpty()){
                    for(Lead leadLoop : leadWithOutCCSList){
                        LeadIdSet.add(leadLoop.Id);
                        if(!LeadGroupNameVsLeads.containsKey(leadLoop.Lead_Group_name__c)){
                            LeadGroupNameVsLeads.put(leadLoop.Lead_Group_name__c,new List<Lead>());
                        }
                        LeadGroupNameVsLeads.get(leadLoop.Lead_Group_name__c).add(leadLoop); 
                        
                    }
                    for(String key : LeadGroupNameVsLeads.keySet()){
                        System.debug(key+' LeadGroupName has '+LeadGroupNameVsLeads.get(key).size()+' Leads');
                        if(key == 'Kampagne 1'){
                            LeadGroupNameVsLeads.put('DFJ - Kampagne 1',LeadGroupNameVsLeads.get(key));
                        } else if(key == 'TD Kampagne 1'){
                            LeadGroupNameVsLeads.put('TDK - Kampagne 1',LeadGroupNameVsLeads.get(key));
                        }            
                    }
                    
                    leadGroupsList = [SELECT Id,Name,telegenta__Call_Campaign__c FROM telegenta__Lead_group__c WHERE Name IN :LeadGroupNameVsLeads.keySet() LIMIT 10000];
                    if(!leadGroupsList.isEmpty()){
                        for(telegenta__Lead_group__c leadGroupInstance : leadGroupsList){
                            if(leadGroupInstance.telegenta__Call_Campaign__c != null){
                                if(leadGroupInstance.Name == 'DFJ - Kampagne 1'){
                                    LeadGroupNameVsCallCampaignId.put('Kampagne 1',leadGroupInstance.telegenta__Call_Campaign__c);                        
                                } else if(leadGroupInstance.Name == 'TDK - Kampagne 1'){
                                    LeadGroupNameVsCallCampaignId.put('TD Kampagne 1',leadGroupInstance.telegenta__Call_Campaign__c);     
                                }
                            }
                        }          
                    }
                }
                System.debug('LeadGroupNameVsCallCampaignId ====>>'+JSON.serialize(LeadGroupNameVsCallCampaignId));
                for(String leadInstance : LeadIdVsLead.keySet()){
                    telegenta__Call_Campaign_State__c callCampaignStateInstance = new telegenta__Call_Campaign_State__c();
                    if(LeadIdVsCallCampaignStates.containsKey(leadInstance)){ 
                        for(telegenta__Call_Campaign_State__c callCampaignStateLoop : LeadIdVsCallCampaignStates.get(leadInstance)){
                            callCampaignStateLoop.telegenta__Unsuccessful_calls__c = LeadIdVsLead.get(leadInstance).telegenta__Unsuccessful_Calls__c == null?0:LeadIdVsLead.get(leadInstance).telegenta__Unsuccessful_Calls__c;
                            callCampaignStateLoop.telegenta__Total_Unsucccessful_Call__c = LeadIdVsLead.get(leadInstance).telegenta__Unsuccessful_Calls__c == null?0:LeadIdVsLead.get(leadInstance).telegenta__Unsuccessful_Calls__c;
                            callCampaignStateLoop.telegenta__Total_Calls__c = LeadIdVsLead.get(leadInstance).telegenta__Total_Calls__c == null?0:LeadIdVsLead.get(leadInstance).telegenta__Total_Calls__c;
                            callCampaignStateLoop.telegenta__Last_Outcome__c = callCampaignStateInstance.telegenta__Last_Outcome__c == null ? outcomeId : callCampaignStateInstance.telegenta__Last_Outcome__c;
                            callCampaignStateLoop.telegenta__Has_appointment__c = true;  
                            callCampaignStateInstance.telegenta__Last_Call_Time__c = Datetime.now();
                            callCampaignStateLoop.telegenta__Next_Call_Time__c = LeadIdVsLead.get(leadInstance).telegenta__Next_Call_Time__c;     
                            callCampaignStateToUpsertList.add(callCampaignStateLoop);
                        }
                    } else{
                        if(LeadIdSet.contains(leadInstance)){
                            callCampaignStateInstance.telegenta__Unsuccessful_calls__c = LeadIdVsLead.get(leadInstance).telegenta__Unsuccessful_Calls__c == null?0:LeadIdVsLead.get(leadInstance).telegenta__Unsuccessful_Calls__c;
                            callCampaignStateInstance.telegenta__Total_Unsucccessful_Call__c = LeadIdVsLead.get(leadInstance).telegenta__Unsuccessful_Calls__c == null?0:LeadIdVsLead.get(leadInstance).telegenta__Unsuccessful_Calls__c;
                            callCampaignStateInstance.telegenta__Total_Calls__c = LeadIdVsLead.get(leadInstance).telegenta__Total_Calls__c == null?0:LeadIdVsLead.get(leadInstance).telegenta__Total_Calls__c;
                            callCampaignStateInstance.telegenta__Last_Call_Time__c = Datetime.now();
                            callCampaignStateInstance.telegenta__Lead__c = leadInstance;
                            callCampaignStateInstance.telegenta__Last_Outcome__c = outcomeId;
                            callCampaignStateInstance.telegenta__Has_appointment__c = true;
                            callCampaignStateInstance.telegenta__Next_Call_Time__c = LeadIdVsLead.get(leadInstance).telegenta__Next_Call_Time__c; 
                            if(LeadGroupNameVsCallCampaignId.containsKey(LeadIdVsLead.get(leadInstance).Lead_Group_name__c)){
                                callCampaignStateInstance.telegenta__Call_Campaign__c = LeadGroupNameVsCallCampaignId.get(LeadIdVsLead.get(leadInstance).Lead_Group_name__c);  
                            }                
                            callCampaignStateToUpsertList.add(callCampaignStateInstance); 
                        }
                    }
                }
                System.debug('callCampaignStateToUpsertList ====>>'+JSON.serialize(callCampaignStateToUpsertList));
                System.debug('callCampaignStateToUpsertList Size====>>'+callCampaignStateToUpsertList.size());
                
                for(telegenta__Call_Campaign_State__c campaignStateLoop : callCampaignStateToUpsertList){
                    if(campaignStateLoop.telegenta__Call_Campaign__c != null){
                        callCampaignStateInstanceToUpsertList.add(campaignStateLoop);
                    }
                    
                }
                System.debug('callCampaignStateInstanceToUpsertList ====>>'+JSON.serialize(callCampaignStateInstanceToUpsertList));
                System.debug('callCampaignStateInstanceToUpsertList Size====>>'+callCampaignStateInstanceToUpsertList.size());
                upsert callCampaignStateInstanceToUpsertList;
            }
        }catch(Exception ex){
            // DR_DialerRules.addErrorLogs('recordId','Inserting/updating call campaign state.',JSON.serialize(ex.getMessage()),'Error','DR_MigrationController.UpdateCallCampaignStateForRecord_Apex',ex.getStackTraceString(),String.valueOf(ex.getLineNumber()));
            System.debug('Error---------'+ex.getMessage()+' At line number'+ex.getLineNumber());
        }
        return null;
    }
}