force-app/main/default/objects/Lead/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Memberships</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DFJ_LeadForMembership_Helper_Test.cls
@isTest
public with sharing class DFJ_LeadForMembership_Helper_Test {
    @isTest
    static void basicTestwithAccount() {
        List<Lead> leadIns = DFJ_TestDataFactory.CreateLeadWithHarAccepteFied(1);
        Test.startTest();
        DFJ_LeadForMembership_Helper.CreateMembership_Apex(leadIns);
        Test.stopTest();
        Membership__c member = [Select Id,Last_Name__c,First_Name__c,Lead__c FROM Membership__c Where Lead__c =: leadIns[0].Id Limit 1];
        System.assertEquals(leadIns[0].Id, member.Lead__c);
    }

    @isTest
    static void createMembershipBySendingEmpty() {
        Test.startTest();
        Boolean success = DFJ_LeadForMembership_Helper.CreateMembership_Apex(null);
        Test.stopTest();
        System.assertEquals(false, success);
    }
}