force-app/main/default/objects/Lead/fields/Phone2__c.field-meta.xml
<CustomField>
    <fullName>Phone2__c</fullName>
    <label>Phone2</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Phone3__c.field-meta.xml
<CustomField>
    <fullName>Phone3__c</fullName>
    <label>Phone3</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Provider_id__c.field-meta.xml
<CustomField>
    <fullName>Provider_id__c</fullName>
    <externalId>true</externalId>
    <label>Provider ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Publisher_name__c.field-meta.xml
<CustomField>
    <fullName>Publisher_name__c</fullName>
    <description>Name of the publisher which created lead</description>
    <label>Publisher name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>eGentic</fullName>
            </value>
            <value>
                <fullName>facebook</fullName>
            </value>
            <value>
                <fullName>website</fullName>
            </value>
            <value>
                <fullName>BoligAdvokat24</fullName>
            </value>
            <value>
                <fullName>DFJ</fullName>
            </value>
            <value>
                <fullName>Danske Seniorer</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Premio</fullName>
            </value>
            <value>
                <fullName>Clovermetrics</fullName>
            </value>
            <value>
                <fullName>Forsikringshjælp.nu</fullName>
            </value>
            <value>
                <fullName>Forbrugsforeningen</fullName>
            </value>
            <value>
                <fullName>Min mave</fullName>
            </value>
            <value>
                <fullName>Nyhedsbreve</fullName>
            </value>
            <value>
                <fullName>Børn i byen</fullName>
            </value>
            <value>
                <fullName>Reshopper</fullName>
            </value>
            <value>
                <fullName>Crowdio</fullName>
            </value>
            <value>
                <fullName>Folkeskolen</fullName>
            </value>
            <value>
                <fullName>Samvirke</fullName>
            </value>
            <value>
                <fullName>HK</fullName>
            </value>
            <value>
                <fullName>Influencer</fullName>
            </value>
            <value>
                <fullName>google</fullName>
            </value>
            <value>
                <fullName>homePage</fullName>
            </value>
            <value>
                <fullName>Inmix</fullName>
            </value>
            <value>
                <fullName>Kundkontakter</fullName>
            </value>
            <value>
                <fullName>Bisnode</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DFJ_checkDuplicacy_Test.cls
/**
 * Created by Shubham Sharma on 03-07-2019.
 */
@isTest
public with sharing class DFJ_checkDuplicacy_Test {

    @isTest
    private static void duplicayCheck(){
        Lead leadInstance = new Lead();
        leadInstance.FirstName = 'TestLead';
        leadInstance.LastName= 'Test Last Name';
        leadInstance.Company = 'Test Company';
        leadInstance.Provider_id__c = '1122';
        leadInstance.Phone='1122334455';
        leadInstance.Phone2__c='1122334455';
        leadInstance.Phone3__c='1122334455';
        leadInstance.Publisher_name__c='Facebook';
        insert leadInstance;

        Lead leadInstance1 = new Lead();
        leadInstance1.FirstName = 'TestLead';
        leadInstance1.LastName= 'Test Last Name';
        leadInstance1.Company = 'Test Company';
        leadInstance1.Provider_id__c = '11221';
        leadInstance1.Phone='1122334455';
        leadInstance.Phone2__c='112233442';
        leadInstance.Phone3__c='1122333';
        leadInstance1.Publisher_name__c='Facebook';
        insert leadInstance1;
    }

}