force-app/main/default/objects/Lead/fields/Provider_id__c.field-meta.xml
<CustomField>
    <fullName>Provider_id__c</fullName>
    <externalId>true</externalId>
    <label>Provider ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/telegenta__Last_Contact_State__c.field-meta.xml
<CustomField>
    <fullName>telegenta__Last_Contact_State__c</fullName>
    <description>Last outcome of call attempt</description>
    <inlineHelpText>Last outcome of call attempt</inlineHelpText>
    <label>Last Contact State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No answer or voicemail</fullName>
            </value>
            <value>
                <fullName>Number busy</fullName>
            </value>
            <value>
                <fullName>Don&apos;t have time right now</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Got appointment</fullName>
                <label>Appointment</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Invalid</fullName>
            </value>
            <value>
                <fullName>Missed Appointment</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/telegenta__Next_Call_Time__c.field-meta.xml
<CustomField>
    <fullName>telegenta__Next_Call_Time__c</fullName>
    <description>Minimum time before lead can be called again</description>
    <inlineHelpText>Minimum time before lead can be called again</inlineHelpText>
    <label>Next Call Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/DFJ_DK.recordType-meta.xml
<RecordType>
    <fullName>DFJ_DK</fullName>
    <active>true</active>
    <businessProcess>Process To distribute leads</businessProcess>
    <label>Denmark</label>
</RecordType>

force-app/main/default/classes/DFJ_UpdateOverdueLeads_Test.cls
@isTest
public class DFJ_UpdateOverdueLeads_Test {
    static testmethod void UpdateOverdueLeads_ApexTest(){
        DFJ_UpdateOverdueLeads sch = new DFJ_UpdateOverdueLeads();
        Lead leadInstance = new Lead();
        leadInstance.FirstName = 'Test';
        leadInstance.LastName = 'Lead';
        leadInstance.Company = 'CA';
        leadInstance.Status = 'Working';
        leadInstance.telegenta__Next_Call_Time__c  = DateTime.Now().addDays(-9);
        leadInstance.telegenta__Last_Contact_State__c   = 'Got appointment';
        leadInstance.Market_Unit__c = '	DFJ_DK';
        leadInstance.Provider_id__c = '	SDAD1111';
        insert leadInstance;

        Group queueInstance = new Group();
        queueInstance.Name = 'Sweden Leads';
        queueInstance.Type='Queue';
		insert queueInstance;

        String CRON_EXP = '0 0 23 1/1 * ? *' ;
        DFJ_UpdateOverdueLeads.scheduleUpdateOverdueLeads('set');

        sch.execute(null);
    }
    
    static testmethod void MethodName2(){
        Group queue2Instance = new Group();
        queue2Instance.Name = 'Sweden Leads';
        queue2Instance.Type='Regular';
		insert queue2Instance;
         DFJ_UpdateOverdueLeads sch = new DFJ_UpdateOverdueLeads();
		sch.execute(null);
    }

}