force-app/main/default/objects/Doc_Fabricator_Setting__c/Doc_Fabricator_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Doc Fabricator Setting</label>
</CustomObject>

force-app/main/default/objects/Doc_Fabricator_Setting__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Journals</relationshipLabel>
    <relationshipName>Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal__c/fields/journal_Deadline__c.field-meta.xml
<CustomField>
    <fullName>journal_Deadline__c</fullName>
    <label>journal Deadline</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Journal__c/fields/Journal_States__c.field-meta.xml
<CustomField>
    <fullName>Journal_States__c</fullName>
    <label>Journal  States</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Journal_States</valueSetName>
    </valueSet>
</CustomField>

feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Journals</relationshipLabel>
    <relationshipName>Journals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Inheritance</fullName>
                <default>true</default>
                <label>Inheritance</label>
            </value>
            <value>
                <fullName>Admin of estate</fullName>
                <label>Bobehandling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Journal__c.field-meta.xml
<CustomField>
    <fullName>Journal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal</label>
    <referenceTo>Journal__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DFJ_ProcessDocFabDocument_Apex.cls
/**
 * @description The DFJ_ProcessDocFabDocument_Apex class is responsible for handling
 * document fabrication processes. It provides methods to interact with the document
 * fabricator settings and retrieve URLs for given records and object API names.
 */

public class DFJ_ProcessDocFabDocument_Apex {

    /**
     * @description The getUrl method is used to retrieve the URL for component
     * dFJ_Process_DocFab_Document.
     *
     * @param recordId The ID of the record for which the URL needs to be
     * retrieved.
     * @param objectApiName The API name of the object for which the URL needs to
     * be retrieved.
     * @return a Url for dFJ_Process_DocFab_Document component.
     */

    @AuraEnabled(Cacheable=true)
    public static String getUrl(String recordId, String objectApiName) {
        try {

            if (String.isNotBlank(recordId) && String.isNotBlank(objectApiName)) {
                String url;

                Doc_Fabricator_Setting__c docFabSetting = Doc_Fabricator_Setting__c.getOrgDefaults();
                if (String.isNotBlank(docFabSetting.URL__c)) {

                    Journal__c journalRecord ;

                    journalRecord = [
                            SELECT Id, Name, Journal_States__c, journal_Deadline__c, LastModifiedDate, CreatedDate, External_record_uuid__c, Type__c,
                                    Account__c, Lead__c
                            FROM Journal__c
                            WHERE
                                    Id = :recordId
                                    OR Account__c = :recordId
                                    OR Lead__c = :recordId
                            WITH SECURITY_ENFORCED
                            ORDER BY LastModifiedDate DESC NULLS LAST
                            LIMIT 1
                    ] ?? null;

                    if (journalRecord != null && journalRecord.External_record_uuid__c != null) {
                        url = docFabSetting.URL__c + 'public/record_templates/' + journalRecord.External_record_uuid__c;
                        return url;
                    }
                }
            }
            return null;
        } catch (Exception e) {
            DFJ_ErrorLogController.addErrorLogs('', 'Get URL', e.getMessage(), 'Error', 'DFJ_ProcessDocFabDocument_Apex.getUrl', '', String.valueOf(e.getLineNumber()));
            return null;
        }
    }

}