force-app/main/default/objects/Google_Auth__c/Google_Auth__c.object-meta.xml
<CustomObject>
    <label>Google Auth</label>
    <nameField>
        <label>Google Auth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Auths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Google_Auth__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Google_Auth__c/fields/Refresh_Token__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Token__c</fullName>
    <label>Refresh Token</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Google_Auth__c/fields/Resource_Id__c.field-meta.xml
<CustomField>
    <fullName>Resource_Id__c</fullName>
    <label>Resource Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Google_Auth__c/fields/Token_Name__c.field-meta.xml
<CustomField>
    <fullName>Token_Name__c</fullName>
    <label>Token Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Google_Auth__c/fields/Token_Type__c.field-meta.xml
<CustomField>
    <fullName>Token_Type__c</fullName>
    <label>Token Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Google_Auth__c/fields/Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>Unique_Id__c</fullName>
    <label>Unique Id</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Google_Auth_Key__mdt/Google_Auth_Key__mdt.object-meta.xml
<CustomObject>
    <label>Google Auth Key</label>
    <pluralLabel>Google Auth Keys</pluralLabel>
</CustomObject>

force-app/main/default/objects/Google_Auth_Key__mdt/fields/Redirect_URI__c.field-meta.xml
<CustomField>
    <fullName>Redirect_URI__c</fullName>
    <label>Redirect URI</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/GoogleCallBackController.cls
public class GoogleCallBackController {
    public String baseUrl { get; set; }
    
    public void handleCallback() {
        
        baseUrl = Url.getOrgDomainURL().toExternalForm();
        String authCode = ApexPages.currentPage().getParameters().get('code');
        system.debug('authCode'+authCode);
        Google_Auth_Key__mdt googleCred = GoogleAuthHelper.getGoogleAuthMetaData();
        
        String endPoint = 'https://oauth2.googleapis.com/token';
        String method = 'POST';
        Map<String,String> header = new Map<String,String>();
        header.put('Content-Type', 'application/x-www-form-urlencoded');
        
        String requestBody = 'code=' + EncodingUtil.urlEncode(authCode, 'UTF-8');
        requestBody += '&client_id=' + EncodingUtil.urlEncode(googleCred.Client_Id__c, 'UTF-8');
        requestBody += '&client_secret=' + EncodingUtil.urlEncode(googleCred.Client_Secret__c, 'UTF-8');
        requestBody += '&redirect_uri=' + EncodingUtil.urlEncode(googleCred.Redirect_URI__c, 'UTF-8');
        requestBody += '&grant_type=authorization_code';
        
        HttpResponse response = GoogleAuthHelper.sendRequest(GoogleAuthHelper.prepareRequest(endPoint, method, header, requestBody));
        if (response.getStatusCode() == 200) {
            Map<String, Object> tokenResponse = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            
            if([SELECT COUNT() FROM Google_Auth__c ] == 1){
                Google_Auth__c gAuth = [Select id,Access_Token__c,Refresh_Token__c, Unique_Id__c, Resource_Id__c, Token_Type__c,Token_Name__c from Google_Auth__c where Token_Name__c = 'Latest' Limit 1   ];
                gAuth.Access_Token__c = (String) tokenResponse.get('access_token');
                if((String) tokenResponse.get('refresh_token') != NULL){
                    gAuth.Refresh_Token__c = (String) tokenResponse.get('refresh_token');
                }
                gAuth.Token_Type__c = (String) tokenResponse.get('token_type');
                TokenRefreshForGoogleDrive.createWatch(gAuth, gAuth.Access_Token__c, false);
            }else{
                Google_Auth__c gAuth = new Google_Auth__c();
                gAuth.Token_Name__c = 'Latest';
                gAuth.Access_Token__c = (String) tokenResponse.get('access_token');
                gAuth.Refresh_Token__c = (String) tokenResponse.get('refresh_token');
                gAuth.Token_Type__c = (String) tokenResponse.get('token_type');
                TokenRefreshForGoogleDrive.createWatch(gAuth, gAuth.Access_Token__c, true);
            }
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Authentication successful'));
        }
    }
    
}