force-app/main/default/objects/Google_Auth__c/Google_Auth__c.object-meta.xml
<CustomObject>
    <label>Google Auth</label>
    <nameField>
        <label>Google Auth Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Auths</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Google_Auth__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <label>Access Token</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Google_Auth__c/fields/Token_Name__c.field-meta.xml
<CustomField>
    <fullName>Token_Name__c</fullName>
    <label>Token Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/GoogleAPIMethods_Test.cls
@isTest
public class GoogleAPIMethods_Test {
    
    @isTest
    public static void TestingAllMethods(){
        Google_Auth__c auth = new Google_Auth__c(
            Token_Name__c = 'Latest',
            Access_Token__c = 'TestAccessToken'
        );
        insert auth;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        GoogleAPIMethods.getLatestAccessToken();
        GoogleAPIMethods.fetchGoogleDriveFileContent('folderId');
        GoogleAPIMethods.getParentFolderDetails('folderId');
        GoogleAPIMethods.getFilesCreatedLastMinute();
        Test.stopTest();
    }
}