force-app/main/default/objects/Journal_Configuration__c/Journal_Configuration__c.object-meta.xml
<CustomObject>
    <label>Journal Configuration</label>
    <nameField>
        <displayFormat>JC-{0000}</displayFormat>
        <label>Journal Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Configuration__c/fields/Journal_Field__c.field-meta.xml
<CustomField>
    <fullName>Journal_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal Field</label>
    <referenceTo>Journal_Field__c</referenceTo>
    <relationshipLabel>Journal Configurations</relationshipLabel>
    <relationshipName>Journal_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Configuration__c/fields/Journal_Section__c.field-meta.xml
<CustomField>
    <fullName>Journal_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal Section</label>
    <referenceTo>Journal_Section__c</referenceTo>
    <relationshipLabel>Journal Configurations</relationshipLabel>
    <relationshipName>Journal_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Configuration__c/fields/Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Journal_Configuration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Journal Configurations</relationshipLabel>
    <relationshipName>Journal_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Field__c/Journal_Field__c.object-meta.xml
<CustomObject>
    <label>Journal Field</label>
    <nameField>
        <label>Journal Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journal Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal_Field__c/fields/Journal_Section__c.field-meta.xml
<CustomField>
    <fullName>Journal_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journal Section</label>
    <referenceTo>Journal_Section__c</referenceTo>
    <relationshipLabel>Journal Fields</relationshipLabel>
    <relationshipName>Journal_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Journal_Field__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <label>Unique Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Journal_Section__c/Journal_Section__c.object-meta.xml
<CustomObject>
    <label>Journal Section</label>
    <nameField>
        <label>Journal Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journal Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/For_Promotion__c.field-meta.xml
<CustomField>
    <fullName>For_Promotion__c</fullName>
    <defaultValue>false</defaultValue>
    <label>For Promotion</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DFJ_JournalFormConfiguration_Test.cls
/**
 * Created by shubh on 23-09-2019.
 */
@isTest
public with sharing class DFJ_JournalFormConfiguration_Test {

    @isTest
    private static void getAllJournalFormMetaData_Apex_Test(){
        Product2 productInstance =new Product2();
        productInstance.Name='test';
        productInstance.productCode='1234';
        productInstance.isActive = true;
        productInstance.For_Promotion__c = true;
        insert productInstance;

        List<Journal_Section__c> journal_sections = new List<Journal_Section__c>();
        Journal_Section__c jsObj = new Journal_Section__c();
        jsObj.Name = 'Test Section';
        jsObj.Unique_Name__c = 'Test Unique Name';
        journal_sections.add(jsObj);
        insert journal_sections;

        Journal_Field__c jfObj = new Journal_Field__c();
        jfObj.Name = 'Test Field';
        jfObj.Journal_Section__c = journal_sections[0].Id;
        jfObj.Unique_Name__c = 'Test Unique Name';
        insert jfObj;

        Journal_Configuration__c jcObj = new Journal_Configuration__c();
        jcObj.Journal_Field__c = jfObj.Id;
        jcObj.Journal_Section__c = journal_sections[0].Id;
        jcObj.Mandatory__c = true;
        jcObj.Product__c = productInstance.Id;
        insert jcObj;

        List<Journal_Configuration__c> journalConfigurationsList = new List<Journal_Configuration__c>();
        Journal_Configuration__c jcObj2 = new Journal_Configuration__c();
        jcObj2.Journal_Field__c = jfObj.Id;
        jcObj2.Journal_Section__c = journal_sections[0].Id;
        jcObj2.Mandatory__c = true;
        jcObj2.Product__c = productInstance.Id;
        journalConfigurationsList.add(jcObj2);

        Test.startTest();
        DFJ_JournalFormConfiguration_Apex.getAllJournalFormMetaData_Apex();
        DFJ_JournalFormConfiguration_Apex.getProductMetadata_Apex(productInstance.Id);
        DFJ_JournalFormConfiguration_Apex.insertSectionANdField_Apex(JSON.serialize(journalConfigurationsList), JSON.serialize(new List<String>{jcObj.Id}));
        Test.stopTest();

    }

}