feature-customer-portal/salesforce/main/default/objects/Journal__c/fields/Market_Unit__c.field-meta.xml
<CustomField>
    <fullName>Market_Unit__c</fullName>
    <label>Market Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Journal__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Inheritance</fullName>
                <default>true</default>
                <label>Inheritance</label>
            </value>
            <value>
                <fullName>Admin of estate</fullName>
                <label>Bobehandling</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Market_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DFJ_DK</fullName>
        <default>true</default>
        <label>Din Familie Jurist</label>
    </customValue>
    <customValue>
        <fullName>FA_SE</fullName>
        <label>dinfamiliejurist.nu</label>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Testamente_SV</fullName>
        <isActive>false</isActive>
        <label>Testamente Sverige</label>
    </customValue>
    <customValue>
        <fullName>Testamente_DK</fullName>
        <isActive>false</isActive>
        <label>Testamente Danmark</label>
    </customValue>
    <masterLabel>Market Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/JournalFileUploadRestServiceTest.cls
@isTest
public class JournalFileUploadRestServiceTest {
    @TestSetup
    static void setupData(){
        Journal__c journal = new Journal__c(Market_Unit__c='FA_SE',Type__c='Inheritance',External_record_uuid__c='TestExtRecId');
        insert journal;
    }

    @isTest
    static void testUploadFileToAccount_Success() {
        Journal__c journal = [SELECT Id, Name from Journal__c LIMIT 1];
        setRestServiceRequest('/services/apexrest/uploadFilesToJournal/'+journal.Name, 'POST', 'Sample file content', new Map<String, String>{'File-Name' => 'TestFile'});
        
        Test.startTest();
        JournalFileUploadRestService.uploadFileToAccount();
        Test.stopTest();
        
        System.assertEquals(200, RestContext.response.statusCode);
        System.assertEquals('File uploaded successfully', RestContext.response.responseBody.toString());
    }
    
    @isTest
    static void testUploadFileToAccount_InvalidJournal() {
        setRestServiceRequest('/services/apexrest/uploadFilesToJournal/InvalidJournal', 'POST', 'Sample file content', new Map<String, String>{'File-Name' => 'TestFile'});

        Test.startTest();
        JournalFileUploadRestService.uploadFileToAccount();
        Test.stopTest();
        
        System.assertEquals(400, RestContext.response.statusCode);
        System.assert(RestContext.response.responseBody.toString().contains('Invalid Journal Name'));
    }
    
    @isTest
    static void testUploadFileToAccount_MissingFileName() {
        Journal__c journal = [SELECT Id, Name from Journal__c LIMIT 1];
        setRestServiceRequest('/services/apexrest/uploadFilesToJournal/'+journal.Name, 'POST', 'Sample file content', null);
        
        Test.startTest();
        JournalFileUploadRestService.uploadFileToAccount();
        Test.stopTest();
        
        System.assertEquals(400, RestContext.response.statusCode);
        System.assert(RestContext.response.responseBody.toString().contains('Either file content or file name is missing'));
    }

    static void setRestServiceRequest(String endpoint, String method, String body, Map<String, String> headers){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestUri = endpoint;
        req.httpMethod = method;
        req.requestBody = Blob.valueOf(body);
        if(headers != null){
            for(String key: headers.keySet()){
                req.headers.put(key, headers.get(key));
            }
        }
        RestContext.request = req;
        RestContext.response = res;
    }
}